import { useState, useCallback, useEffect } from "react";
import { useLocation, Link } from "react-router-dom";
import {
  useCarouselGenerator,
  CarouselData,
  PostType,
  POST_TYPE_LABELS,
  CONTENT_PILLARS,
  DESIGN_STYLES,
  FONT_OPTIONS,
  COLOR_PALETTES,
  CarouselSlide,
  WeekContent
} from "@/hooks/useCarouselGenerator";
import { useGenerations } from "@/hooks/useGenerations";
import { useCalendarItems } from "@/hooks/useCalendarItems";
import { ScheduleDialog } from "@/components/ScheduleDialog";
import { ColorPicker } from "@/components/ColorPicker";
import { PhotoSelectionDialog } from "@/components/PhotoSelectionDialog";
import { downloadCarouselAsZip } from "@/lib/downloadZip";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Badge } from "@/components/ui/badge";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Progress } from "@/components/ui/progress";
import {
  Loader2, Sparkles, Copy, Save, ChevronLeft, ChevronRight,
  Plus, Trash2, Image, RefreshCw, Wand2, Edit3, Check, ArrowLeft, CalendarPlus,
  Calendar, Palette, Type, Images, Download, ArrowRight, Lightbulb
} from "lucide-react";
import { CarouselPreviewStage } from "@/components/carousel/CarouselPreviewStage";
import { useToast } from "@/hooks/use-toast";
import { SlideToolbar } from "@/components/carousel/SlideToolbar";
import { exportSlideAsImage } from "@/utils/exportCarousel";
import { useAuth } from "@/hooks/useAuth";
import { useCarouselPersistence } from "@/hooks/useCarouselPersistence";
import { useBrand } from "@/contexts/BrandContext";

export default function CarouselCreator() {
  const { toast } = useToast();
  const location = useLocation();
  const state = location.state as { initialData?: CarouselData; metadata?: any; autoGenerateDesign?: boolean } | null;
  const { saveGeneration } = useGenerations();
  const { addItem: addCalendarItem } = useCalendarItems();
  const { user } = useAuth();
  const { brand } = useBrand();
  const { saveCarousel, isSaving: isSavingCloud } = useCarouselPersistence();
  const {
    carousel,
    weekContent,
    setCarousel,
    isGenerating,
    isGeneratingDesign,
    isGeneratingWeek,
    isGeneratingAllDesigns,
    designProgress,
    designSettings,
    setDesignSettings,
    isBrandLocked,
    currentSlideIndex,
    setCurrentSlideIndex,
    generateCarousel,
    generateSlideDesign,
    generateAllSlideDesigns,
    generateWeekContent,
    selectWeekContentForEdit,
    updateSlide,
    updateLegenda,
    addSlide,
    removeSlide,
    resetCarousel,
    resetWeekContent,
  } = useCarouselGenerator();

  const [useCustomColors, setUseCustomColors] = useState(false);

  // Form state
  const [topic, setTopic] = useState("");
  const [postType, setPostType] = useState<PostType>("ESTRATEGIA_UTIL");
  const [contentPillar, setContentPillar] = useState("Educativo");
  const [customInstructions, setCustomInstructions] = useState("");
  const [editingSlide, setEditingSlide] = useState<number | null>(null);
  const [copied, setCopied] = useState(false);
  const [showScheduleDialog, setShowScheduleDialog] = useState(false);
  const [savedGenerationId, setSavedGenerationId] = useState<string | null>(null);
  const [isDownloading, setIsDownloading] = useState(false);
  const [mode, setMode] = useState<"single" | "week">("single");
  const [editingWeekItem, setEditingWeekItem] = useState<string | null>(null);
  const [showPhotoDialog, setShowPhotoDialog] = useState(false);
  const [photoTargetIndex, setPhotoTargetIndex] = useState<number | null>(null);

  // Handlers for SlideToolbar
  const duplicateSlide = (index: number) => {
    if (!carousel) return;
    const slideToDuplicate = carousel.slides[index];
    const newSlides = [...carousel.slides];
    const duplicatedSlide = {
      ...slideToDuplicate,
      numero: index + 2,
      imageUrl: undefined // Don't copy the rendered image
    };
    newSlides.splice(index + 1, 0, duplicatedSlide);
    newSlides.forEach((s, i) => s.numero = i + 1);
    setCarousel({ ...carousel, slides: newSlides });
    setCurrentSlideIndex(index + 1);
    toast({ title: "Slide duplicado!" });
  };

  const moveSlide = (index: number, direction: number) => {
    if (!carousel) return;
    const newIndex = index + direction;
    if (newIndex < 0 || newIndex >= carousel.slides.length) return;

    const newSlides = [...carousel.slides];
    const [movedSlide] = newSlides.splice(index, 1);
    newSlides.splice(newIndex, 0, movedSlide);
    newSlides.forEach((s, i) => s.numero = i + 1);

    setCarousel({ ...carousel, slides: newSlides });
    setCurrentSlideIndex(newIndex);
  };

  const handleCloudSave = async () => {
    if (!carousel || !user) return;
    const result = await saveCarousel(carousel, user.id, brand);
    if (result && result.id) {
      setCarousel({ ...carousel, id: result.id });
    }
  };

  const scrollToDesign = () => {
    const designPanel = document.getElementById("design-settings-card");
    if (designPanel) {
      designPanel.scrollIntoView({ behavior: "smooth", block: "center" });
    }
  };

  const scrollToEditor = () => {
    const editorPanel = document.getElementById("editor-panel");
    if (editorPanel) {
      editorPanel.scrollIntoView({ behavior: "smooth", block: "start" });
    }
  };

  // Load initial data from navigation state
  useEffect(() => {
    if (state?.initialData && !carousel) {
      setCarousel(state.initialData);
      if (state.metadata?.topic) setTopic(state.metadata.topic);
      if (state.metadata?.theme) setTopic(state.metadata.theme);
      if (state.metadata?.postType) setPostType(state.metadata.postType);
      if (state.metadata?.contentPillar) setContentPillar(state.metadata.contentPillar);
      if (state.metadata?.offer) setCustomInstructions(`Oferta / CTA: ${state.metadata.offer}`);

      // Auto-generate designs if requested
      if (state.autoGenerateDesign) {
        toast({ title: "Iniciando geração visual...", description: "Aplicando sua identidade visual em todos os slides." });
        handleGenerateAllDesigns();
      }
    }
  }, [state, carousel, setCarousel, toast]);

  // Week content form
  const [weekTopics, setWeekTopics] = useState<{ topic: string; postType: PostType; contentPillar: string }[]>([
    { topic: "", postType: "ESTRATEGIA_UTIL", contentPillar: "Educativo" },
    { topic: "", postType: "PROMESSA", contentPillar: "Autoridade" },
    { topic: "", postType: "COMO_FIZ", contentPillar: "Conexão/Bastidores" },
    { topic: "", postType: "DOR_EVENTO", contentPillar: "Conversão/Venda" },
    { topic: "", postType: "ALCANCE", contentPillar: "Entretenimento" },
  ]);

  const handleGenerate = async () => {
    if (!topic.trim()) {
      toast({ variant: "destructive", title: "Digite um tema" });
      return;
    }
    await generateCarousel(topic, postType, contentPillar, customInstructions);
  };

  const handleGenerateWeek = async () => {
    const validTopics = weekTopics.filter(t => t.topic.trim());
    if (validTopics.length === 0) {
      toast({ variant: "destructive", title: "Adicione pelo menos um tema" });
      return;
    }
    await generateWeekContent(validTopics);
  };

  const handleEditWeekItem = (item: WeekContent) => {
    setEditingWeekItem(item.id);
    selectWeekContentForEdit(item.id);
  };

  const handleBackToWeekList = () => {
    setEditingWeekItem(null);
    resetCarousel();
  };

  const handleGenerateDesign = async (index: number) => {
    await generateSlideDesign(index, designSettings.style, {
      primary: designSettings.primaryColor,
      secondary: designSettings.secondaryColor,
    }, designSettings.fontFamily, carousel?.slides[index]?.backgroundImageUrl);
  };

  const handleSelectPhoto = (index: number) => {
    setPhotoTargetIndex(index);
    setShowPhotoDialog(true);
  };

  const onPhotoSelected = (url: string) => {
    if (photoTargetIndex !== null) {
      updateSlide(photoTargetIndex, { backgroundImageUrl: url });
      setPhotoTargetIndex(null);
    }
  };

  const handleGenerateAllDesigns = async () => {
    await generateAllSlideDesigns();
  };

  const updateWeekTopic = (index: number, updates: Partial<{ topic: string; postType: PostType; contentPillar: string }>) => {
    setWeekTopics(prev => prev.map((t, i) => i === index ? { ...t, ...updates } : t));
  };

  const addWeekTopic = () => {
    if (weekTopics.length < 7) {
      setWeekTopics(prev => [...prev, { topic: "", postType: "ESTRATEGIA_UTIL", contentPillar: "Educativo" }]);
    }
  };

  const removeWeekTopic = (index: number) => {
    if (weekTopics.length > 1) {
      setWeekTopics(prev => prev.filter((_, i) => i !== index));
    }
  };

  const handleCopyLegenda = async () => {
    if (!carousel?.legenda) return;
    await navigator.clipboard.writeText(carousel.legenda);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
    toast({ title: "Legenda copiada!" });
  };

  const handleSave = async () => {
    if (!carousel) return;

    const result = await saveGeneration({
      tipo: "post",
      subtipo: "carrossel",
      specialist: "social_media_manager",
      titulo: carousel.titulo,
      output_content: JSON.stringify(carousel),
      input_data: { topic, postType, contentPillar },
      favorito: false,
      tags: [postType.toLowerCase(), contentPillar.toLowerCase()],
    });

    if (!result.error && result.data?.id) {
      setSavedGenerationId(result.data.id);
    }

    toast({ title: "Salvo na biblioteca!" });
  };

  const handleSchedule = async (data: { date: string; tipo: string; titulo: string }) => {
    await addCalendarItem({
      data: data.date,
      tipo: data.tipo,
      titulo: data.titulo,
      generation_id: savedGenerationId || undefined,
    });
  };

  const handleDownloadZip = async () => {
    if (!carousel) return;

    const hasImages = carousel.slides.some(s => s.imageUrl);
    if (!hasImages) {
      toast({ variant: "destructive", title: "Gere os designs primeiro" });
      return;
    }

    setIsDownloading(true);
    try {
      await downloadCarouselAsZip(carousel.slides, carousel.titulo);
      toast({ title: "Download iniciado!" });
    } catch (error) {
      toast({
        variant: "destructive",
        title: "Erro no download",
        description: error instanceof Error ? error.message : "Tente novamente"
      });
    } finally {
      setIsDownloading(false);
    }
  };

  const currentSlide = carousel?.slides[currentSlideIndex];

  return (
    <div className="min-h-screen bg-gradient-to-br from-background via-background to-muted/20">
      {/* Header */}
      <header className="border-b bg-background/80 backdrop-blur-sm sticky top-0 z-50">
        <div className="container flex items-center justify-between h-14 px-4">
          <div className="flex items-center gap-3">
            {editingWeekItem ? (
              <Button variant="ghost" size="icon" onClick={handleBackToWeekList}>
                <ArrowLeft className="h-4 w-4" />
              </Button>
            ) : (
              <Button variant="ghost" size="icon" asChild>
                <Link to="/"><ArrowLeft className="h-4 w-4" /></Link>
              </Button>
            )}
            <div>
              <h1 className="font-semibold">
                {editingWeekItem ? "Editando Post" : "Gerador de Carrossel"}
              </h1>
              <p className="text-xs text-muted-foreground">
                {editingWeekItem ? "Voltar para lista da semana" : "Crie posts que convertem"}
              </p>
            </div>
          </div>
          {carousel && (
            <div className="flex gap-2">
              {editingWeekItem && (
                <Button variant="outline" size="sm" onClick={handleBackToWeekList}>
                  <Check className="h-4 w-4 mr-2" /> Concluir Edição
                </Button>
              )}
              {!editingWeekItem && (
                <Button variant="outline" size="sm" onClick={resetCarousel}>
                  <RefreshCw className="h-4 w-4 mr-2" /> Novo
                </Button>
              )}
              <Button
                variant="outline"
                size="sm"
                onClick={handleDownloadZip}
                disabled={isDownloading || !carousel.slides.some(s => s.imageUrl)}
              >
                {isDownloading ? (
                  <Loader2 className="h-4 w-4 animate-spin" />
                ) : (
                  <><Download className="h-4 w-4 mr-2" /> ZIP</>
                )}
              </Button>
              <Button variant="outline" size="sm" onClick={() => setShowScheduleDialog(true)}>
                <CalendarPlus className="h-4 w-4 mr-2" /> Agendar
              </Button>
              <Button size="sm" onClick={handleSave}>
                <Save className="h-4 w-4 mr-2" /> Salvar
              </Button>
            </div>
          )}
        </div>
      </header>

      <main className="container px-4 py-6">
        {/* Week content list view */}
        {weekContent.length > 0 && !carousel && !editingWeekItem ? (
          <div className="max-w-4xl mx-auto space-y-6">
            <div className="flex items-center justify-between">
              <div>
                <h2 className="text-xl font-bold">Semana Gerada</h2>
                <p className="text-sm text-muted-foreground">Clique em um post para editar</p>
              </div>
              <Button variant="outline" onClick={resetWeekContent}>
                <RefreshCw className="h-4 w-4 mr-2" /> Nova Semana
              </Button>
            </div>

            <div className="grid gap-4">
              {weekContent.map((item, index) => (
                <Card
                  key={item.id}
                  className="cursor-pointer hover:border-primary transition-colors"
                  onClick={() => handleEditWeekItem(item)}
                >
                  <CardContent className="p-4">
                    <div className="flex items-center justify-between">
                      <div className="flex items-center gap-3">
                        <div className="w-10 h-10 rounded-lg bg-primary/10 flex items-center justify-center">
                          <span className="font-semibold text-primary">{index + 1}</span>
                        </div>
                        <div>
                          <p className="font-medium line-clamp-1">{item.carousel?.titulo || item.topic}</p>
                          <div className="flex gap-2 mt-1">
                            <Badge variant="outline" className="text-xs">{POST_TYPE_LABELS[item.postType]}</Badge>
                            <Badge variant="secondary" className="text-xs">{item.contentPillar}</Badge>
                          </div>
                        </div>
                      </div>
                      <div className="flex items-center gap-2">
                        <Badge variant={item.status === "edited" ? "default" : "secondary"}>
                          {item.status === "edited" ? "Editado" : "Gerado"}
                        </Badge>
                        <Edit3 className="h-4 w-4 text-muted-foreground" />
                      </div>
                    </div>
                  </CardContent>
                </Card>
              ))}
            </div>
          </div>
        ) : !carousel ? (
          <div className="max-w-3xl mx-auto pt-10 space-y-8 animate-in fade-in slide-in-from-bottom-4 duration-500">
            <div className="text-center space-y-4">
              <div className="inline-flex items-center justify-center p-3 bg-primary/10 rounded-full mb-4">
                <Sparkles className="w-8 h-8 text-primary" />
              </div>
              <h1 className="text-4xl font-bold tracking-tight text-foreground">
                O que vamos criar hoje?
              </h1>
              <p className="text-lg text-muted-foreground max-w-xl mx-auto">
                Descreva o tema e nossa IA criará o roteiro, design e copy persuasiva para seu carrossel.
              </p>
            </div>

            <Card className="border-2 shadow-lg hover:shadow-xl transition-all duration-300">
              <CardContent className="p-6 space-y-4">
                <div className="relative">
                  <Textarea
                    value={topic}
                    onChange={(e) => setTopic(e.target.value)}
                    placeholder="Ex: 5 dicas de nutrição para mulheres na menopausa com foco em redução de inchaço..."
                    className="min-h-[120px] text-lg p-4 resize-none border-muted focus-visible:ring-primary/20 bg-muted/5 rounded-xl"
                  />
                  <div className="absolute bottom-3 right-3 text-xs text-muted-foreground">
                    {topic.length} caracteres
                  </div>
                </div>

                <div className="flex items-center justify-between pt-2">
                  <div className="flex gap-2">
                    <span className="text-xs font-medium text-muted-foreground flex items-center gap-1">
                      <Lightbulb className="w-3 h-3" /> Dica: Seja específico no público-alvo
                    </span>
                  </div>

                  <Button
                    onClick={handleGenerate}
                    disabled={isGenerating || !topic.trim()}
                    size="lg"
                    className="rounded-full px-8 font-semibold shadow-md hover:shadow-lg transition-all"
                  >
                    {isGenerating ? (
                      <>Gerando Estratégia...</>
                    ) : (
                      <>
                        Gerar Carrossel <ArrowRight className="ml-2 w-4 h-4" />
                      </>
                    )}
                  </Button>
                </div>
              </CardContent>
            </Card>
          </div>
        ) : (
          /* Carousel Editor */
          <div className="space-y-6">
            {carousel && (
              <div className="const-container">
                {(() => {
                  const currentSlide = carousel.slides[currentSlideIndex];
                  const totalSlides = carousel.slides.length;

                  return (
                    <div className="grid lg:grid-cols-2 gap-6">
                      {/* Column 1: Preview & Navigation */}
                      <div className="space-y-4">
                        <div className="flex flex-col w-full max-w-lg mx-auto">
                          <SlideToolbar
                            onEditContent={scrollToEditor}
                            onEditStyle={scrollToDesign}
                            onDelete={() => removeSlide(currentSlideIndex)}
                            onDuplicate={() => duplicateSlide(currentSlideIndex)}
                            onMoveLeft={() => moveSlide(currentSlideIndex, -1)}
                            onMoveRight={() => moveSlide(currentSlideIndex, 1)}
                            canMoveLeft={currentSlideIndex > 0}
                            canMoveRight={currentSlideIndex < totalSlides - 1}
                            currentSlideText={currentSlide?.headline || ""}
                            onUpdateText={(newText) => updateSlide(currentSlideIndex, { headline: newText })}
                          />

                          <CarouselPreviewStage
                            currentIndex={currentSlideIndex}
                            totalSlides={totalSlides}
                          >
                            <div id="active-slide-container" className="w-full h-full relative overflow-hidden">
                              {currentSlide?.imageUrl ? (
                                <img
                                  src={currentSlide.imageUrl}
                                  alt={`Slide ${currentSlideIndex + 1}`}
                                  className="w-full h-full object-cover"
                                />
                              ) : (
                                <div className="w-full h-full flex flex-col items-center justify-center p-8 bg-gradient-to-br from-muted/50 to-muted relative">
                                  {currentSlide?.backgroundImageUrl && (
                                    <img
                                      src={currentSlide.backgroundImageUrl}
                                      alt="Background"
                                      className="absolute inset-0 w-full h-full object-cover opacity-30 mix-blend-overlay"
                                    />
                                  )}
                                  <Badge className="mb-4 relative z-10" variant="outline">
                                    Slide {currentSlideIndex + 1}/{totalSlides}
                                  </Badge>

                                  <div className="text-center max-w-sm relative z-10">
                                    {currentSlide?.destaque && (
                                      <p className="text-sm text-primary font-medium mb-2">{currentSlide.destaque}</p>
                                    )}
                                    <h3 className="text-xl font-bold mb-3 leading-tight">{currentSlide?.headline}</h3>
                                    {currentSlide?.subtexto && (
                                      <p className="text-muted-foreground text-sm whitespace-pre-line">{currentSlide.subtexto}</p>
                                    )}
                                  </div>
                                </div>
                              )}
                            </div>
                          </CarouselPreviewStage>

                          <div className="mt-6 flex justify-center gap-3">
                            <Button
                              onClick={() => exportSlideAsImage('active-slide-container', `slide-${currentSlideIndex + 1}`)}
                              className="gap-2 shadow-lg hover:shadow-xl transition-all"
                              variant="outline"
                            >
                              <Download className="h-4 w-4" /> Baixar HD
                            </Button>

                            <Button
                              onClick={handleCloudSave}
                              disabled={isSavingCloud || !carousel}
                              className="gap-2 shadow-lg hover:shadow-xl transition-all bg-gradient-to-r from-indigo-600 to-purple-600"
                            >
                              {isSavingCloud ? <Loader2 className="h-4 w-4 animate-spin" /> : <Save className="h-4 w-4" />}
                              {isSavingCloud ? "Salvando..." : "Salvar na Nuvem"}
                            </Button>
                          </div>
                        </div>

                        <div className="flex items-center justify-between gap-2 p-2 bg-muted/30 rounded-lg">
                          <Button variant="outline" size="sm" onClick={() => handleSelectPhoto(currentSlideIndex)}>
                            <Image className="h-4 w-4 mr-2" /> Alterar Fundo
                          </Button>
                          {currentSlide?.imageUrl && (
                            <Button variant="outline" size="sm" onClick={() => handleGenerateDesign(currentSlideIndex)}>
                              <RefreshCw className="h-4 w-4 mr-2" /> Regenerar
                            </Button>
                          )}
                        </div>

                        {/* Slide Navigation */}
                        <div className="flex items-center justify-between">
                          <Button
                            variant="outline"
                            size="icon"
                            onClick={() => setCurrentSlideIndex(Math.max(0, currentSlideIndex - 1))}
                            disabled={currentSlideIndex === 0}
                          >
                            <ChevronLeft className="h-4 w-4" />
                          </Button>

                          <ScrollArea className="flex-1 mx-4">
                            <div className="flex gap-2 justify-center">
                              {carousel.slides.map((slide, i) => (
                                <button
                                  key={i}
                                  onClick={() => setCurrentSlideIndex(i)}
                                  className={`w-10 h-10 rounded-lg text-xs font-medium transition-all ${i === currentSlideIndex
                                    ? "bg-primary text-primary-foreground"
                                    : "bg-muted hover:bg-muted/80"
                                    } ${slide.imageUrl ? "ring-2 ring-green-500" : ""}`}
                                >
                                  {i + 1}
                                </button>
                              ))}
                              <button
                                onClick={() => addSlide(carousel.slides.length - 1)}
                                className="w-10 h-10 rounded-lg border-2 border-dashed border-muted-foreground/30 flex items-center justify-center hover:border-primary transition-colors"
                              >
                                <Plus className="h-4 w-4" />
                              </button>
                            </div>
                          </ScrollArea>

                          <Button
                            variant="outline"
                            size="icon"
                            onClick={() => setCurrentSlideIndex(Math.min(carousel.slides.length - 1, currentSlideIndex + 1))}
                            disabled={currentSlideIndex === carousel.slides.length - 1}
                          >
                            <ChevronRight className="h-4 w-4" />
                          </Button>
                        </div>

                        {/* Design Settings Card */}
                        <Card id="design-settings-card" className="overflow-hidden bg-card/50 backdrop-blur-xl border-primary/10 shadow-xl">
                          <CardHeader className="pb-3 bg-primary/5">
                            <div className="flex items-center justify-between">
                              <div className="flex items-center gap-2">
                                <Palette className="h-4 w-4 text-primary animate-pulse" />
                                <CardTitle className="text-sm font-bold tracking-tight">Personalização Visual</CardTitle>
                              </div>
                              {isBrandLocked && (
                                <Badge variant="secondary" className="text-[10px] px-2 py-0 h-5">Marca Travada</Badge>
                              )}
                            </div>
                          </CardHeader>
                          <CardContent className="p-5 space-y-6">
                            <div className="grid grid-cols-2 gap-4">
                              <div className="space-y-2">
                                <label className="text-[10px] font-bold uppercase tracking-widest text-muted-foreground flex items-center gap-2">
                                  <Sparkles className="h-3 w-3" /> Estilo
                                </label>
                                <Select value={designSettings.style} onValueChange={(v) => setDesignSettings({ ...designSettings, style: v })} disabled={isBrandLocked}>
                                  <SelectTrigger className="bg-background/40 border-primary/20 hover:border-primary/50 transition-all">
                                    <SelectValue />
                                  </SelectTrigger>
                                  <SelectContent>
                                    {DESIGN_STYLES.map((s) => (
                                      <SelectItem key={s.id} value={s.id}>{s.label}</SelectItem>
                                    ))}
                                  </SelectContent>
                                </Select>
                              </div>

                              <div className="space-y-2">
                                <label className="text-[10px] font-bold uppercase tracking-widest text-muted-foreground flex items-center gap-2">
                                  <Type className="h-3 w-3" /> Fonte
                                </label>
                                <Select value={designSettings.fontFamily} onValueChange={(v) => setDesignSettings({ ...designSettings, fontFamily: v })} disabled={isBrandLocked}>
                                  <SelectTrigger className="bg-background/40 border-primary/20 hover:border-primary/50 transition-all">
                                    <SelectValue />
                                  </SelectTrigger>
                                  <SelectContent>
                                    {FONT_OPTIONS.map((f) => (
                                      <SelectItem key={f.id} value={f.id}>{f.label}</SelectItem>
                                    ))}
                                  </SelectContent>
                                </Select>
                              </div>
                            </div>

                            {!isBrandLocked && (
                              <div className="space-y-4">
                                <label className="text-[10px] font-bold uppercase tracking-widest text-muted-foreground flex items-center gap-2">
                                  <Palette className="h-3 w-3" /> Identidade Cromática
                                </label>

                                <div className="grid grid-cols-4 sm:grid-cols-6 gap-2">
                                  {COLOR_PALETTES.map((p) => (
                                    <button
                                      key={p.id}
                                      onClick={() => setDesignSettings({ ...designSettings, primaryColor: p.primary, secondaryColor: p.secondary })}
                                      className={`group relative p-1 rounded-xl border-2 transition-all hover:scale-105 active:scale-95 ${designSettings.primaryColor === p.primary ? "border-primary shadow-lg shadow-primary/20" : "border-transparent hover:border-muted-foreground/30"
                                        }`}
                                      title={p.label}
                                    >
                                      <div className="flex h-10 w-full rounded-lg overflow-hidden shadow-inner">
                                        <div className="w-1/2 h-full" style={{ backgroundColor: p.primary }} />
                                        <div className="w-1/2 h-full" style={{ backgroundColor: p.secondary }} />
                                      </div>
                                      {designSettings.primaryColor === p.primary && (
                                        <div className="absolute -top-1 -right-1 bg-primary text-white rounded-full p-0.5 shadow-md">
                                          <Check className="h-2 w-2" />
                                        </div>
                                      )}
                                    </button>
                                  ))}
                                </div>

                                <div className="relative flex items-center gap-3 py-2">
                                  <div className="flex-1 h-px bg-gradient-to-r from-transparent via-muted to-transparent" />
                                  <span className="text-[9px] text-muted-foreground font-bold uppercase tracking-[0.2em]">Ou Customizar</span>
                                  <div className="flex-1 h-px bg-gradient-to-r from-transparent via-muted to-transparent" />
                                </div>

                                <div className="grid grid-cols-2 gap-4">
                                  <div className="space-y-2">
                                    <div className="flex gap-2">
                                      <ColorPicker
                                        color={designSettings.primaryColor}
                                        onChange={(c) => setDesignSettings({ ...designSettings, primaryColor: c })}
                                      />
                                      <Input
                                        value={designSettings.primaryColor}
                                        onChange={(e) => setDesignSettings({ ...designSettings, primaryColor: e.target.value })}
                                        className="h-9 text-[10px] font-mono uppercase bg-background/40 border-primary/20"
                                      />
                                    </div>
                                  </div>
                                  <div className="space-y-2">
                                    <div className="flex gap-2">
                                      <ColorPicker
                                        color={designSettings.secondaryColor}
                                        onChange={(c) => setDesignSettings({ ...designSettings, secondaryColor: c })}
                                      />
                                      <Input
                                        value={designSettings.secondaryColor}
                                        onChange={(e) => setDesignSettings({ ...designSettings, secondaryColor: e.target.value })}
                                        className="h-9 text-[10px] font-mono uppercase bg-background/40 border-primary/20"
                                      />
                                    </div>
                                  </div>
                                </div>
                              </div>
                            )}

                            <div className="grid grid-cols-2 gap-3 pt-2">
                              <Button
                                onClick={() => handleGenerateDesign(currentSlideIndex)}
                                disabled={isGeneratingDesign || isGeneratingAllDesigns}
                                className="relative overflow-hidden group shadow-lg shadow-primary/20 hover:shadow-primary/40 active:scale-95 transition-all"
                              >
                                <div className="absolute inset-0 bg-gradient-to-r from-primary to-primary-foreground opacity-0 group-hover:opacity-10 transition-opacity" />
                                {isGeneratingDesign ? (
                                  <>
                                    <Loader2 className="h-4 w-4 animate-spin mr-2" />
                                    Gerando...
                                  </>
                                ) : (
                                  <>
                                    <Wand2 className="h-4 w-4 mr-2 group-hover:rotate-12 transition-transform" />
                                    Design Atual
                                  </>
                                )}
                              </Button>
                              <Button
                                onClick={handleGenerateAllDesigns}
                                disabled={isGeneratingDesign || isGeneratingAllDesigns}
                                variant="secondary"
                                className="group shadow-md hover:shadow-lg active:scale-95 transition-all border border-primary/10"
                              >
                                {isGeneratingAllDesigns ? (
                                  <>
                                    <Loader2 className="h-4 w-4 animate-spin mr-2" />
                                    {designProgress.current}/{designProgress.total}
                                  </>
                                ) : (
                                  <>
                                    <Images className="h-4 w-4 mr-2 group-hover:scale-110 transition-transform" />
                                    Toda Visual
                                  </>
                                )}
                              </Button>
                            </div>

                            {isGeneratingAllDesigns && (
                              <div className="space-y-1">
                                <div className="flex justify-between text-[10px] text-muted-foreground uppercase font-bold tracking-widest">
                                  <span>Progresso</span>
                                  <span>{Math.round((designProgress.current / designProgress.total) * 100)}%</span>
                                </div>
                                <Progress value={(designProgress.current / designProgress.total) * 100} className="h-1.5 bg-primary/10" />
                              </div>
                            )}
                          </CardContent>
                        </Card>
                      </div>

                      {/* Column 2: Editor Panel */}
                      <div id="editor-panel" className="space-y-4">
                        <Tabs defaultValue="slides">
                          <TabsList className="grid w-full grid-cols-2">
                            <TabsTrigger value="slides">Slides</TabsTrigger>
                            <TabsTrigger value="legenda">Legenda</TabsTrigger>
                          </TabsList>

                          <TabsContent value="slides" className="space-y-4">
                            {/* Current Slide Editor */}
                            <Card>
                              <CardHeader className="pb-3">
                                <div className="flex items-center justify-between">
                                  <CardTitle className="text-sm">Slide {currentSlideIndex + 1}</CardTitle>
                                  <div className="flex gap-2">
                                    <Button
                                      variant="ghost"
                                      size="icon"
                                      onClick={() => setEditingSlide(editingSlide === currentSlideIndex ? null : currentSlideIndex)}
                                    >
                                      <Edit3 className="h-4 w-4" />
                                    </Button>
                                    {carousel.slides.length > 2 && (
                                      <Button
                                        variant="ghost"
                                        size="icon"
                                        onClick={() => removeSlide(currentSlideIndex)}
                                      >
                                        <Trash2 className="h-4 w-4 text-destructive" />
                                      </Button>
                                    )}
                                  </div>
                                </div>
                              </CardHeader>
                              <CardContent className="space-y-3">
                                <div className="space-y-2">
                                  <label className="text-xs text-muted-foreground">Destaque</label>
                                  <Input
                                    value={currentSlide?.destaque || ""}
                                    onChange={(e) => updateSlide(currentSlideIndex, { destaque: e.target.value })}
                                    placeholder="Palavra ou frase de destaque"
                                  />
                                </div>
                                <div className="space-y-2">
                                  <label className="text-xs text-muted-foreground">Headline</label>
                                  <Textarea
                                    value={currentSlide?.headline || ""}
                                    onChange={(e) => updateSlide(currentSlideIndex, { headline: e.target.value })}
                                    placeholder="Texto principal do slide"
                                    rows={3}
                                  />
                                </div>
                                <div className="space-y-2">
                                  <label className="text-xs text-muted-foreground">Subtexto</label>
                                  <Textarea
                                    value={currentSlide?.subtexto || ""}
                                    onChange={(e) => updateSlide(currentSlideIndex, { subtexto: e.target.value })}
                                    placeholder="Texto de apoio (opcional)"
                                    rows={4}
                                  />
                                </div>
                              </CardContent>
                            </Card>

                            {/* All Slides Overview */}
                            <Card>
                              <CardHeader className="pb-3">
                                <CardTitle className="text-sm">Todos os Slides</CardTitle>
                              </CardHeader>
                              <CardContent>
                                <ScrollArea className="h-[200px]">
                                  <div className="space-y-2">
                                    {carousel.slides.map((slide, i) => (
                                      <div
                                        key={i}
                                        className={`p-3 rounded-lg border cursor-pointer transition-all ${i === currentSlideIndex ? "border-primary bg-primary/5" : "hover:bg-muted/50"
                                          }`}
                                        onClick={() => setCurrentSlideIndex(i)}
                                      >
                                        <div className="flex items-center justify-between">
                                          <Badge variant="outline" className="text-xs">
                                            {slide.tipo}
                                          </Badge>
                                          {slide.imageUrl && (
                                            <Check className="h-3 w-3 text-green-500" />
                                          )}
                                        </div>
                                        <p className="text-sm mt-1 line-clamp-2">{slide.headline}</p>
                                      </div>
                                    ))}
                                  </div>
                                </ScrollArea>
                              </CardContent>
                            </Card>
                          </TabsContent>

                          <TabsContent value="legenda" className="space-y-4">
                            <Card>
                              <CardHeader className="pb-3">
                                <div className="flex items-center justify-between">
                                  <CardTitle className="text-sm">Legenda do Post</CardTitle>
                                  <Button variant="ghost" size="sm" onClick={handleCopyLegenda}>
                                    {copied ? <Check className="h-4 w-4" /> : <Copy className="h-4 w-4" />}
                                  </Button>
                                </div>
                              </CardHeader>
                              <CardContent>
                                <Textarea
                                  value={carousel.legenda}
                                  onChange={(e) => updateLegenda(e.target.value)}
                                  placeholder="Legenda para o Instagram..."
                                  rows={12}
                                  className="resize-none"
                                />
                              </CardContent>
                            </Card>

                            {carousel.cta_stories && (
                              <Card>
                                <CardHeader className="pb-3">
                                  <CardTitle className="text-sm">Sugestão para Stories</CardTitle>
                                </CardHeader>
                                <CardContent>
                                  <p className="text-sm text-muted-foreground">{carousel.cta_stories}</p>
                                </CardContent>
                              </Card>
                            )}
                          </TabsContent>
                        </Tabs>
                      </div>
                    </div>
                  );
                })()}
              </div>
            )}
          </div>
        )}
      </main>

      {/* Schedule Dialog */}
      <ScheduleDialog
        open={showScheduleDialog}
        onOpenChange={setShowScheduleDialog}
        onSchedule={handleSchedule}
        defaultTitle={carousel?.titulo || topic}
        defaultTipo="carrossel"
      />

      <PhotoSelectionDialog
        open={showPhotoDialog}
        onOpenChange={setShowPhotoDialog}
        onSelect={onPhotoSelected}
        selectedUrl={carousel?.slides[currentSlideIndex]?.backgroundImageUrl}
      />
    </div>
  );
}
