import { useState, useCallback, useEffect } from "react";
import { useLocation, Link } from "react-router-dom";
import {
  useCarouselGenerator,
  CarouselData,
  PostType,
  POST_TYPE_LABELS,
  CONTENT_PILLARS,
  DESIGN_STYLES,
  FONT_OPTIONS,
  COLOR_PALETTES,
  CarouselSlide,
  WeekContent
} from "@/hooks/useCarouselGenerator";
import { useGenerations } from "@/hooks/useGenerations";
import { useCalendarItems } from "@/hooks/useCalendarItems";
import { ScheduleDialog } from "@/components/ScheduleDialog";
import { ColorPicker } from "@/components/ColorPicker";
import { PhotoSelectionDialog } from "@/components/PhotoSelectionDialog";
import { downloadCarouselAsZip } from "@/lib/downloadZip";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Badge } from "@/components/ui/badge";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Progress } from "@/components/ui/progress";
import {
  Loader2, Sparkles, Copy, Save, ChevronLeft, ChevronRight,
  Plus, Trash2, Image, RefreshCw, Wand2, Edit3, Check, ArrowLeft, CalendarPlus,
  Calendar, Palette, Type, Images, Download, ArrowRight, Lightbulb, Target
} from "lucide-react";
import { Label } from "@/components/ui/label";
import { CarouselSlideEditor } from "@/components/carousel/CarouselSlideEditor";
import { useToast } from "@/hooks/use-toast";
import { cn } from "@/lib/utils";
import { SlideToolbar } from "@/components/carousel/SlideToolbar";
import { exportSlideAsImage } from "@/utils/exportCarousel";
import { useAuth } from "@/hooks/useAuth";
import { useCarouselPersistence } from "@/hooks/useCarouselPersistence";
import { useBrand } from "@/contexts/BrandContext";

export default function CarouselCreator() {
  const { toast } = useToast();
  const location = useLocation();
  const state = location.state as { initialData?: CarouselData; metadata?: any; autoGenerateDesign?: boolean } | null;
  const { saveGeneration } = useGenerations();
  const { addItem: addCalendarItem } = useCalendarItems();
  const { user } = useAuth();
  const { brand } = useBrand();
  const { saveCarousel, isSaving: isSavingCloud } = useCarouselPersistence();
  const {
    carousel,
    weekContent,
    setCarousel,
    isGenerating,
    isGeneratingDesign,
    isGeneratingWeek,
    isGeneratingAllDesigns,
    designProgress,
    designSettings,
    setDesignSettings,
    isBrandLocked,
    currentSlideIndex,
    setCurrentSlideIndex,
    generateCarousel,
    generateSlideDesign,
    generateAllSlideDesigns,
    generateWeekContent,
    selectWeekContentForEdit,
    updateSlide,
    updateLegenda,
    addSlide,
    removeSlide,
    resetCarousel,
    resetWeekContent,
    refineText,
  } = useCarouselGenerator();

  const [useCustomColors, setUseCustomColors] = useState(false);

  // Form state
  const [topic, setTopic] = useState("");
  const [postType, setPostType] = useState<PostType>("ESTRATEGIA_UTIL");
  const [contentPillar, setContentPillar] = useState("Educativo");
  const [customInstructions, setCustomInstructions] = useState("");
  const [editingSlide, setEditingSlide] = useState<number | null>(null);
  const [copied, setCopied] = useState(false);
  const [showScheduleDialog, setShowScheduleDialog] = useState(false);
  const [savedGenerationId, setSavedGenerationId] = useState<string | null>(null);
  const [isDownloading, setIsDownloading] = useState(false);
  const [mode, setMode] = useState<"single" | "week">("single");
  const [editingWeekItem, setEditingWeekItem] = useState<string | null>(null);
  const [showPhotoDialog, setShowPhotoDialog] = useState(false);
  const [photoTargetIndex, setPhotoTargetIndex] = useState<number | null>(null);

  // Handlers for SlideToolbar
  const duplicateSlide = (index: number) => {
    if (!carousel) return;
    const slideToDuplicate = carousel.slides[index];
    const newSlides = [...carousel.slides];
    const duplicatedSlide = {
      ...slideToDuplicate,
      numero: index + 2,
      imageUrl: undefined // Don't copy the rendered image
    };
    newSlides.splice(index + 1, 0, duplicatedSlide);
    newSlides.forEach((s, i) => s.numero = i + 1);
    setCarousel({ ...carousel, slides: newSlides });
    setCurrentSlideIndex(index + 1);
    toast({ title: "Slide duplicado!" });
  };

  const moveSlide = (index: number, direction: number) => {
    if (!carousel) return;
    const newIndex = index + direction;
    if (newIndex < 0 || newIndex >= carousel.slides.length) return;

    const newSlides = [...carousel.slides];
    const [movedSlide] = newSlides.splice(index, 1);
    newSlides.splice(newIndex, 0, movedSlide);
    newSlides.forEach((s, i) => s.numero = i + 1);

    setCarousel({ ...carousel, slides: newSlides });
    setCurrentSlideIndex(newIndex);
  };

  const handleCloudSave = async () => {
    if (!carousel || !user) return;
    const result = await saveCarousel(carousel, user.id, brand);
    if (result && result.id) {
      setCarousel({ ...carousel, id: result.id });
    }
  };

  const scrollToDesign = () => {
    const designPanel = document.getElementById("design-settings-card");
    if (designPanel) {
      designPanel.scrollIntoView({ behavior: "smooth", block: "center" });
    }
  };


  // Load initial data from navigation state
  useEffect(() => {
    if (state?.initialData && !carousel) {
      setCarousel(state.initialData);
      if (state.metadata?.topic) setTopic(state.metadata.topic);
      if (state.metadata?.theme) setTopic(state.metadata.theme);
      if (state.metadata?.postType) setPostType(state.metadata.postType);
      if (state.metadata?.contentPillar) setContentPillar(state.metadata.contentPillar);
      if (state.metadata?.offer) setCustomInstructions(`Oferta / CTA: ${state.metadata.offer}`);

      // Auto-generate designs if requested
      if (state.autoGenerateDesign) {
        toast({ title: "Iniciando geração visual...", description: "Aplicando sua identidade visual em todos os slides." });
        handleGenerateAllDesigns();
      }
    }
  }, [state, carousel, setCarousel, toast]);

  // Week content form
  const [weekTopics, setWeekTopics] = useState<{ topic: string; postType: PostType; contentPillar: string }[]>([
    { topic: "", postType: "STORYTELLING_RESULTADO", contentPillar: "Autoridade" },
    { topic: "", postType: "CONTRA_INTUITIVO", contentPillar: "Educativo" },
    { topic: "", postType: "QUEBRA_OBJECAO", contentPillar: "Conexão" },
    { topic: "", postType: "LISTA_AUTORIDADE", contentPillar: "Autoridade" },
    { topic: "", postType: "CTA_DIRETO", contentPillar: "Conversão" },
  ]);

  const handleGenerate = async () => {
    if (!topic.trim()) {
      toast({ variant: "destructive", title: "Digite um tema" });
      return;
    }
    // Assuming 'strategy' is defined elsewhere or will be defined.
    // For now, it's added as per instruction, but will cause a reference error if not defined.
    // strategy Context is removed if not defined, or passed if available. 
    // Usually it should come from the profile or a local state.
    await generateCarousel(topic, postType, contentPillar, customInstructions);
  };

  const handleGenerateWeek = async () => {
    const validTopics = weekTopics.filter(t => t.topic.trim());
    if (validTopics.length === 0) {
      toast({ variant: "destructive", title: "Adicione pelo menos um tema" });
      return;
    }
    await generateWeekContent(validTopics);
  };

  const handleEditWeekItem = (item: WeekContent) => {
    setEditingWeekItem(item.id);
    selectWeekContentForEdit(item.id);
  };

  const handleBackToWeekList = () => {
    setEditingWeekItem(null);
    resetCarousel();
  };

  const handleGenerateDesign = async (index: number) => {
    await generateSlideDesign(index, designSettings.style, {
      primary: designSettings.primaryColor,
      secondary: designSettings.secondaryColor,
    }, designSettings.fontFamily, carousel?.slides[index]?.backgroundImageUrl);
  };

  const handleSelectPhoto = (index: number) => {
    setPhotoTargetIndex(index);
    setShowPhotoDialog(true);
  };

  const onPhotoSelected = (url: string) => {
    if (photoTargetIndex !== null) {
      updateSlide(photoTargetIndex, { backgroundImageUrl: url });
      setPhotoTargetIndex(null);
    }
  };

  const handleGenerateAllDesigns = async () => {
    await generateAllSlideDesigns();
  };

  const updateWeekTopic = (index: number, updates: Partial<{ topic: string; postType: PostType; contentPillar: string }>) => {
    setWeekTopics(prev => prev.map((t, i) => i === index ? { ...t, ...updates } : t));
  };

  const addWeekTopic = () => {
    if (weekTopics.length < 7) {
      setWeekTopics(prev => [...prev, { topic: "", postType: "ESTRATEGIA_UTIL", contentPillar: "Educativo" }]);
    }
  };

  const removeWeekTopic = (index: number) => {
    if (weekTopics.length > 1) {
      setWeekTopics(prev => prev.filter((_, i) => i !== index));
    }
  };

  const handleCopyLegenda = async () => {
    if (!carousel?.legenda) return;
    await navigator.clipboard.writeText(carousel.legenda);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
    toast({ title: "Legenda copiada!" });
  };

  const handleSave = async () => {
    if (!carousel) return;

    const result = await saveGeneration({
      tipo: "post",
      subtipo: "carrossel",
      specialist: "social_media_manager",
      titulo: carousel.titulo,
      output_content: JSON.stringify(carousel),
      input_data: { topic, postType, contentPillar },
      favorito: false,
      tags: [postType.toLowerCase(), contentPillar.toLowerCase()],
    });

    if (!result.error && result.data?.id) {
      setSavedGenerationId(result.data.id);
    }

    toast({ title: "Salvo com sucesso!" });
  };

  const handleSchedule = async (data: { date: string; tipo: string; titulo: string }) => {
    await addCalendarItem({
      data: data.date,
      tipo: data.tipo,
      titulo: data.titulo,
      generation_id: savedGenerationId || undefined,
    });
  };

  const handleDownloadZip = async () => {
    if (!carousel) return;

    const hasImages = carousel.slides.some(s => s.imageUrl);
    if (!hasImages) {
      toast({ variant: "destructive", title: "Gere os designs primeiro" });
      return;
    }

    setIsDownloading(true);
    try {
      await downloadCarouselAsZip(carousel.slides, carousel.titulo);
      toast({ title: "Download iniciado!" });
    } catch (error) {
      toast({
        variant: "destructive",
        title: "Erro no download",
        description: error instanceof Error ? error.message : "Tente novamente"
      });
    } finally {
      setIsDownloading(false);
    }
  };

  const currentSlide = carousel?.slides[currentSlideIndex];

  return (
    <div className="min-h-screen bg-gradient-to-br from-background via-background to-muted/20">
      {/* Header */}
      <header className="border-b bg-background/80 backdrop-blur-sm sticky top-0 z-50">
        <div className="container flex items-center justify-between h-14 px-4">
          <div className="flex items-center gap-3">
            {editingWeekItem ? (
              <Button variant="ghost" size="icon" onClick={handleBackToWeekList}>
                <ArrowLeft className="h-4 w-4" />
              </Button>
            ) : (
              <Button variant="ghost" size="icon" asChild>
                <Link to="/"><ArrowLeft className="h-4 w-4" /></Link>
              </Button>
            )}
            <div>
              <h1 className="font-semibold">
                {editingWeekItem ? "Editando Post" : "Gerador de Carrossel"}
              </h1>
              <p className="text-xs text-muted-foreground">
                {editingWeekItem ? "Voltar para lista da semana" : "Crie posts que convertem"}
              </p>
            </div>
          </div>
          {carousel && (
            <div className="flex gap-2">
              {editingWeekItem && (
                <Button variant="outline" size="sm" onClick={handleBackToWeekList}>
                  <Check className="h-4 w-4 mr-2" /> Concluir Edição
                </Button>
              )}
              {!editingWeekItem && (
                <Button variant="outline" size="sm" onClick={resetCarousel}>
                  <RefreshCw className="h-4 w-4 mr-2" /> Novo
                </Button>
              )}
              <Button
                variant="outline"
                size="sm"
                onClick={handleDownloadZip}
                disabled={isDownloading || !carousel.slides.some(s => s.imageUrl)}
              >
                {isDownloading ? (
                  <Loader2 className="h-4 w-4 animate-spin" />
                ) : (
                  <><Download className="h-4 w-4 mr-2" /> ZIP</>
                )}
              </Button>
              <Button variant="outline" size="sm" onClick={() => setShowScheduleDialog(true)}>
                <CalendarPlus className="h-4 w-4 mr-2" /> Agendar
              </Button>
              <Button size="sm" onClick={handleSave}>
                <Save className="h-4 w-4 mr-2" /> Salvar
              </Button>
            </div>
          )}
        </div>
      </header>

      <main className="container px-4 py-6">
        {/* Week content list view */}
        {weekContent.length > 0 && !carousel && !editingWeekItem ? (
          <div className="max-w-4xl mx-auto space-y-6">
            <div className="flex items-center justify-between">
              <div>
                <h2 className="text-xl font-bold">Semana Gerada</h2>
                <p className="text-sm text-muted-foreground">Clique em um post para editar</p>
              </div>
              <Button variant="outline" onClick={resetWeekContent}>
                <RefreshCw className="h-4 w-4 mr-2" /> Nova Semana
              </Button>
            </div>

            <div className="grid gap-4">
              {weekContent.map((item, index) => (
                <Card
                  key={item.id}
                  className="cursor-pointer hover:border-primary transition-colors"
                  onClick={() => handleEditWeekItem(item)}
                >
                  <CardContent className="p-4">
                    <div className="flex items-center justify-between">
                      <div className="flex items-center gap-3">
                        <div className="w-10 h-10 rounded-lg bg-primary/10 flex items-center justify-center">
                          <span className="font-semibold text-primary">{index + 1}</span>
                        </div>
                        <div>
                          <p className="font-medium line-clamp-1">{item.carousel?.titulo || item.topic}</p>
                          <div className="flex gap-2 mt-1">
                            <Badge variant="outline" className="text-xs">{POST_TYPE_LABELS[item.postType]}</Badge>
                            <Badge variant="secondary" className="text-xs">{item.contentPillar}</Badge>
                          </div>
                        </div>
                      </div>
                      <div className="flex items-center gap-2">
                        <Badge variant={item.status === "edited" ? "default" : "secondary"}>
                          {item.status === "edited" ? "Editado" : "Gerado"}
                        </Badge>
                        <Edit3 className="h-4 w-4 text-muted-foreground" />
                      </div>
                    </div>
                  </CardContent>
                </Card>
              ))}
            </div>
          </div>
        ) : !carousel ? (
          <div className="max-w-3xl mx-auto pt-10 space-y-8 animate-in fade-in slide-in-from-bottom-4 duration-500">
            <div className="text-center space-y-4">
              <div className="inline-flex items-center justify-center p-3 bg-primary/10 rounded-full mb-4">
                <Sparkles className="w-8 h-8 text-primary" />
              </div>
              <h1 className="text-4xl font-bold tracking-tight text-foreground">
                O que vamos criar hoje?
              </h1>
              <p className="text-lg text-muted-foreground max-w-xl mx-auto">
                Descreva o tema e nossa IA criará o roteiro, design e copy persuasiva para seu carrossel.
              </p>
            </div>

            <Card className="border-2 shadow-lg hover:shadow-xl transition-all duration-300">
              <CardContent className="p-6 space-y-4">
                <div className="relative">
                  <Textarea
                    value={topic}
                    onChange={(e) => setTopic(e.target.value)}
                    placeholder="Ex: 5 dicas de nutrição para mulheres na menopausa com foco em redução de inchaço..."
                    className="min-h-[120px] text-lg p-4 resize-none border-muted focus-visible:ring-primary/20 bg-muted/5 rounded-xl"
                  />
                  <div className="absolute bottom-3 right-3 text-xs text-muted-foreground">
                    {topic.length} caracteres
                  </div>
                </div>

                <div className="flex items-center justify-between pt-2">
                  <div className="flex gap-2">
                    <span className="text-xs font-medium text-muted-foreground flex items-center gap-1">
                      <Lightbulb className="w-3 h-3" /> Dica: Seja específico no público-alvo
                    </span>
                  </div>

                  <Button
                    onClick={handleGenerate}
                    disabled={isGenerating || !topic.trim()}
                    size="lg"
                    className="rounded-full px-8 font-semibold shadow-md hover:shadow-lg transition-all"
                  >
                    {isGenerating ? (
                      <>Gerando Estratégia...</>
                    ) : (
                      <>
                        Gerar Carrossel <ArrowRight className="ml-2 w-4 h-4" />
                      </>
                    )}
                  </Button>
                </div>
              </CardContent>
            </Card>
          </div>
        ) : (
          /* Carousel Editor */
          <div className="space-y-6">
            {carousel && (
              <div className="max-w-6xl mx-auto animate-in fade-in slide-in-from-bottom-4 duration-700">
                {/* Estratégia Ativa Indicator */}
                <div className="mb-8 flex flex-col md:flex-row items-center justify-between p-6 bg-white/40 backdrop-blur-md border border-primary/20 rounded-[32px] shadow-sm gap-4">
                  <div className="flex items-center gap-4">
                    <div className="p-3 bg-primary/10 rounded-2xl">
                      <Target className="h-6 w-6 text-primary" />
                    </div>
                    <div>
                      <p className="text-[10px] font-black uppercase tracking-[0.2em] text-primary/60">Estratégia Ativa</p>
                      <h2 className="font-extrabold text-xl tracking-tight">{carousel.titulo}</h2>
                    </div>
                  </div>
                  <div className="flex gap-2">
                    <Badge variant="secondary" className="bg-primary/10 text-primary border-none px-4 py-1.5 rounded-xl font-bold">{POST_TYPE_LABELS[postType] || 'Estratégia'}</Badge>
                    <Badge variant="outline" className="border-primary/20 px-4 py-1.5 rounded-xl font-medium">{contentPillar}</Badge>
                  </div>
                </div>

                <div className="grid lg:grid-cols-[1fr_320px] gap-10 items-start">
                  {/* Column 1: Canva-style Editor */}
                  <div className="space-y-8">
                    <div className="flex flex-col w-full">
                      <div className="mb-4">
                        <SlideToolbar
                          onEditContent={() => { }} // Direct editing is now always on
                          onEditStyle={scrollToDesign}
                          onDelete={() => removeSlide(currentSlideIndex)}
                          onDuplicate={() => duplicateSlide(currentSlideIndex)}
                          onMoveLeft={() => moveSlide(currentSlideIndex, -1)}
                          onMoveRight={() => moveSlide(currentSlideIndex, 1)}
                          canMoveLeft={currentSlideIndex > 0}
                          canMoveRight={currentSlideIndex < (carousel?.slides?.length || 0) - 1}
                          currentSlideText={carousel?.slides[currentSlideIndex]?.headline || ""}
                          onUpdateText={(newText) => updateSlide(currentSlideIndex, { headline: newText })}
                        />
                      </div>

                      {/* Direct Editor Stage */}
                      <div className="relative group transition-all duration-700 ease-in-out bg-slate-50/50 dark:bg-slate-900/10 p-4 md:p-16 rounded-[48px] border border-slate-200/40 flex justify-center shadow-[inset_0_2px_10px_rgba(0,0,0,0.02)] min-h-[500px]">
                        <div className="relative">
                          {/* Realistic Sombra */}
                          <div className="absolute -inset-4 bg-gradient-to-tr from-primary/10 via-transparent to-primary/5 blur-3xl opacity-50" />

                          <div id="active-slide-container" className="relative w-[340px] aspect-[4/5] bg-white rounded-xl shadow-[0_30px_60px_-15px_rgba(0,0,0,0.2)] overflow-hidden ring-1 ring-black/5 transform hover:scale-[1.01] transition-all duration-500">
                            <CarouselSlideEditor
                              slide={carousel.slides[currentSlideIndex]}
                              index={currentSlideIndex}
                              onUpdate={updateSlide}
                              onSelectBackground={() => handleSelectPhoto(currentSlideIndex)}
                              onRefine={refineText}
                            />

                            {/* Carousel Indicator Bolinhas */}
                            <div className="absolute bottom-4 left-0 right-0 flex justify-center gap-1.5 z-20 pointer-events-none">
                              {carousel.slides.map((_, i) => (
                                <div
                                  key={i}
                                  className={cn(
                                    "w-1.5 h-1.5 rounded-full transition-all duration-300",
                                    i === currentSlideIndex ? "bg-primary w-4 scale-110" : "bg-slate-200"
                                  )}
                                />
                              ))}
                            </div>
                          </div>
                        </div>
                      </div>

                      <div className="mt-8 flex flex-wrap justify-center gap-4">
                        <Button
                          onClick={() => exportSlideAsImage('active-slide-container', `slide-${currentSlideIndex + 1}`)}
                          className="h-14 px-8 gap-3 rounded-[20px] shadow-lg hover:shadow-xl transition-all border-slate-200 bg-white"
                          variant="outline"
                        >
                          <Download className="h-5 w-5 text-primary" /> Exportar Slide HD
                        </Button>

                        <Button
                          onClick={handleCloudSave}
                          disabled={isSavingCloud}
                          className="h-14 px-8 gap-3 rounded-[20px] shadow-xl hover:shadow-2xl transition-all bg-gradient-to-r from-primary to-primary/80 border-none"
                        >
                          {isSavingCloud ? <Loader2 className="h-5 w-5 animate-spin" /> : <Save className="h-5 w-5" />}
                          {isSavingCloud ? "Salvando..." : "Salvar na Estratégia"}
                        </Button>
                      </div>
                    </div>

                    {/* Slide Selector Strip */}
                    <div className="flex items-center justify-between gap-4 p-5 bg-white/90 backdrop-blur-xl rounded-[32px] border border-slate-200/50 shadow-xl overflow-hidden animate-in slide-in-from-bottom-8 duration-1000">
                      <Button
                        variant="ghost"
                        size="icon"
                        className="rounded-full h-12 w-12 hover:bg-primary/5 transition-colors"
                        onClick={() => setCurrentSlideIndex(Math.max(0, currentSlideIndex - 1))}
                        disabled={currentSlideIndex === 0}
                      >
                        <ChevronLeft className="h-8 w-8 text-slate-400" />
                      </Button>

                      <ScrollArea className="flex-1 w-full max-w-lg">
                        <div className="flex gap-4 justify-center py-2 px-6">
                          {carousel.slides.map((slide, i) => (
                            <button
                              key={i}
                              onClick={() => setCurrentSlideIndex(i)}
                              className={cn(
                                "min-w-[64px] h-20 rounded-2xl text-xs font-black transition-all border-4 relative overflow-hidden group/btn",
                                i === currentSlideIndex
                                  ? "border-primary bg-primary text-primary-foreground scale-110 shadow-xl"
                                  : "bg-white border-slate-50 text-slate-400 hover:border-slate-100 hover:text-slate-600"
                              )}
                            >
                              {i + 1}
                              {slide.imageUrl && (
                                <div className="absolute top-1 right-1">
                                  <div className="w-2 h-2 bg-green-500 rounded-full shadow-[0_0_8px_rgba(34,197,94,0.6)]" />
                                </div>
                              )}
                              <div className="absolute inset-0 bg-primary/5 opacity-0 group-hover/btn:opacity-100 transition-opacity" />
                            </button>
                          ))}
                          <Button
                            variant="ghost"
                            onClick={() => addSlide(carousel.slides.length - 1)}
                            className="min-w-[64px] h-20 rounded-2xl border-4 border-dashed border-slate-100 text-slate-300 hover:text-primary hover:border-primary/30 transition-all p-0 bg-slate-50/50"
                          >
                            <Plus className="h-8 w-8" />
                          </Button>
                        </div>
                      </ScrollArea>

                      <Button
                        variant="ghost"
                        size="icon"
                        className="rounded-full h-12 w-12 hover:bg-primary/5 transition-colors"
                        onClick={() => setCurrentSlideIndex(Math.min(carousel.slides.length - 1, currentSlideIndex + 1))}
                        disabled={currentSlideIndex === carousel.slides.length - 1}
                      >
                        <ChevronRight className="h-8 w-8 text-slate-400" />
                      </Button>
                    </div>
                  </div>

                  {/* Column 2: Brand & Copy */}
                  <div className="space-y-8 animate-in slide-in-from-right-8 duration-700">
                    <Card className="border-none shadow-2xl bg-white/95 backdrop-blur-xl overflow-hidden rounded-[32px] border border-white/20">
                      <CardHeader className="bg-primary/5 pb-4 border-b border-primary/10">
                        <CardTitle className="text-sm font-black flex items-center gap-2 uppercase tracking-widest text-primary/80">
                          <Palette className="h-4 w-4" /> Kit de Marca
                        </CardTitle>
                      </CardHeader>
                      <CardContent className="p-8 space-y-8">
                        <div className="space-y-4">
                          <Label className="text-[10px] font-black uppercase tracking-[0.2em] opacity-40">Tipografia</Label>
                          <div className="p-4 bg-slate-50/50 border border-slate-100 rounded-2xl flex items-center justify-between group cursor-default">
                            <span className="font-extrabold tracking-tight text-slate-800">{brand.fontHeading}</span>
                            <Badge variant="secondary" className="bg-primary/10 text-primary border-none text-[9px] font-black uppercase">Ativo</Badge>
                          </div>
                        </div>

                        <div className="space-y-4">
                          <Label className="text-[10px] font-black uppercase tracking-[0.2em] opacity-40">Paleta Cromática</Label>
                          <div className="grid grid-cols-2 gap-4">
                            <div className="p-5 bg-white border border-slate-100 rounded-[24px] space-y-3 shadow-sm hover:shadow-md transition-shadow">
                              <div className="h-14 rounded-2xl shadow-inner relative group" style={{ backgroundColor: brand.primary }}>
                                <div className="absolute inset-0 bg-white/10 opacity-0 group-hover:opacity-100 transition-opacity rounded-2xl" />
                              </div>
                              <span className="text-[10px] font-black font-mono text-center block opacity-40 group-hover:opacity-100 transition-opacity">{brand.primary}</span>
                            </div>
                            <div className="p-5 bg-white border border-slate-100 rounded-[24px] space-y-3 shadow-sm hover:shadow-md transition-shadow">
                              <div className="h-14 rounded-2xl shadow-inner relative group" style={{ backgroundColor: brand.secondary }}>
                                <div className="absolute inset-0 bg-white/10 opacity-0 group-hover:opacity-100 transition-opacity rounded-2xl" />
                              </div>
                              <span className="text-[10px] font-black font-mono text-center block opacity-40 group-hover:opacity-100 transition-opacity">{brand.secondary}</span>
                            </div>
                          </div>
                        </div>

                        <Button
                          variant="outline"
                          className="w-full h-14 rounded-2xl font-bold gap-4 border-slate-200 hover:bg-primary hover:text-white hover:border-primary transition-all shadow-sm group"
                          onClick={() => handleSelectPhoto(currentSlideIndex)}
                        >
                          <Images className="h-5 w-5 text-primary group-hover:text-white transition-colors" /> Personalizar Fundo
                        </Button>
                      </CardContent>
                    </Card>

                    <Card className="border-none shadow-2xl bg-white/95 backdrop-blur-xl rounded-[32px] overflow-hidden border border-white/20">
                      <CardHeader className="pb-4 border-b bg-primary/5 border-primary/10">
                        <CardTitle className="text-sm font-black flex items-center gap-2 uppercase tracking-widest text-primary/80">
                          <Edit3 className="h-4 w-4" /> Copy de Elite
                        </CardTitle>
                      </CardHeader>
                      <CardContent className="p-8 space-y-6">
                        <div className="bg-slate-50/80 rounded-3xl p-6 border border-slate-100 shadow-inner">
                          <Textarea
                            value={carousel.legenda}
                            onChange={(e) => updateLegenda(e.target.value)}
                            className="min-h-[300px] text-sm leading-relaxed border-none bg-transparent resize-none p-0 focus-visible:ring-0 scrollbar-hide"
                            placeholder="Editando a copy persuasiva..."
                          />
                        </div>
                        <Button
                          variant="default"
                          className="w-full h-14 rounded-2xl font-black gap-4 shadow-xl shadow-primary/20 hover:scale-[1.02] transition-transform"
                          onClick={handleCopyLegenda}
                        >
                          <Copy className="h-5 w-5" /> Copiar Legenda
                        </Button>
                      </CardContent>
                    </Card>
                  </div>
                </div>
              </div>
            )}
          </div>
        )}
      </main>

      {/* Schedule Dialog */}
      <ScheduleDialog
        open={showScheduleDialog}
        onOpenChange={setShowScheduleDialog}
        onSchedule={handleSchedule}
        defaultTitle={carousel?.titulo || topic}
        defaultTipo="carrossel"
      />

      <PhotoSelectionDialog
        open={showPhotoDialog}
        onOpenChange={setShowPhotoDialog}
        onSelect={onPhotoSelected}
        selectedUrl={carousel?.slides[currentSlideIndex]?.backgroundImageUrl}
      />
    </div>
  );
}
