import { useState, useCallback, useEffect } from "react";
import { useLocation, Link } from "react-router-dom";
import {
  useCarouselGenerator,
  CarouselData,
  PostType,
  POST_TYPE_LABELS,
  POST_TYPE_DESCRIPTIONS,
  CONTENT_PILLARS,
  DESIGN_STYLES,
  FONT_OPTIONS,
  COLOR_PALETTES,
  CarouselSlide,
  WeekContent,
  FunnelStage,
  FUNNEL_STAGE_LABELS,
  FUNNEL_STAGE_DESCRIPTIONS,
  FUNNEL_STAGE_ICONS,
  CtaStyle,
  CTA_STYLE_LABELS,
  NarrativeElement,
  NARRATIVE_ELEMENT_LABELS,
  ContentFormat,
  CONTENT_FORMAT_LABELS,
  CONTENT_FORMAT_DESCRIPTIONS,
  CONTENT_FORMAT_ICONS,
} from "@/hooks/useCarouselGenerator";
import { useGenerations } from "@/hooks/useGenerations";
import { useCalendarItems } from "@/hooks/useCalendarItems";
import { ScheduleDialog } from "@/components/ScheduleDialog";
import { ColorPicker } from "@/components/ColorPicker";
import { PhotoSelectionDialog } from "@/components/PhotoSelectionDialog";
import { downloadCarouselAsZip } from "@/lib/downloadZip";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Badge } from "@/components/ui/badge";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Progress } from "@/components/ui/progress";
import {
  Loader2, Sparkles, Copy, Save, ChevronLeft, ChevronRight,
  Plus, Trash2, Image, RefreshCw, Wand2, Edit3, Check, ArrowLeft, CalendarPlus,
  Calendar, Palette, Type, Images, Download, ArrowRight, Lightbulb, Target
} from "lucide-react";
import { Label } from "@/components/ui/label";
import { CarouselSlideEditor } from "@/components/carousel/CarouselSlideEditor";
import { useToast } from "@/hooks/use-toast";
import { cn } from "@/lib/utils";
import { SlideToolbar } from "@/components/carousel/SlideToolbar";
import { exportSlideAsImage } from "@/utils/exportCarousel";
import { useAuth } from "@/hooks/useAuth";
import { useCarouselPersistence } from "@/hooks/useCarouselPersistence";
import { useBrand } from "@/contexts/BrandContext";

export default function CarouselCreator() {
  const { toast } = useToast();
  const location = useLocation();
  const state = location.state as { initialData?: CarouselData; metadata?: any; autoGenerateDesign?: boolean; topic?: string; preselectedFormat?: string } | null;
  const { saveGeneration } = useGenerations();
  const { addItem: addCalendarItem } = useCalendarItems();
  const { user } = useAuth();
  const { brand } = useBrand();
  const { saveCarousel, isSaving: isSavingCloud } = useCarouselPersistence();
  const {
    carousel,
    weekContent,
    setCarousel,
    isGenerating,
    isGeneratingDesign,
    isGeneratingWeek,
    isGeneratingAllDesigns,
    designProgress,
    designSettings,
    setDesignSettings,
    isBrandLocked,
    currentSlideIndex,
    setCurrentSlideIndex,
    generateCarousel,
    generateSlideDesign,
    generateAllSlideDesigns,
    generateWeekContent,
    selectWeekContentForEdit,
    updateSlide,
    updateLegenda,
    addSlide,
    removeSlide,
    resetCarousel,
    resetWeekContent,
    refineText,
    currentContentFormat,
  } = useCarouselGenerator();

  const [useCustomColors, setUseCustomColors] = useState(false);

  // Form state
  const [topic, setTopic] = useState("");
  const [contentFormat, setContentFormat] = useState<ContentFormat>("carousel");
  const [postType, setPostType] = useState<PostType>("LISTA_AUTORIDADE");
  const [contentPillar, setContentPillar] = useState("Educativo");
  const [funnelStage, setFunnelStage] = useState<FunnelStage>("EVENTOS_DOR");
  const [ctaStyle, setCtaStyle] = useState<CtaStyle>("auto");
  const [narrativeElement, setNarrativeElement] = useState<NarrativeElement>("auto");
  const [customInstructions, setCustomInstructions] = useState("");
  const [editingSlide, setEditingSlide] = useState<number | null>(null);
  const [copied, setCopied] = useState(false);
  const [showScheduleDialog, setShowScheduleDialog] = useState(false);
  const [savedGenerationId, setSavedGenerationId] = useState<string | null>(null);
  const [isDownloading, setIsDownloading] = useState(false);
  const [mode, setMode] = useState<"single" | "week">("single");
  const [editingWeekItem, setEditingWeekItem] = useState<string | null>(null);
  const [showPhotoDialog, setShowPhotoDialog] = useState(false);
  const [photoTargetIndex, setPhotoTargetIndex] = useState<number | null>(null);
  const [showAdvanced, setShowAdvanced] = useState(false);

  // Handlers for SlideToolbar
  const duplicateSlide = (index: number) => {
    if (!carousel) return;
    const slideToDuplicate = carousel.slides[index];
    const newSlides = [...carousel.slides];
    const duplicatedSlide = {
      ...slideToDuplicate,
      numero: index + 2,
      imageUrl: undefined // Don't copy the rendered image
    };
    newSlides.splice(index + 1, 0, duplicatedSlide);
    newSlides.forEach((s, i) => s.numero = i + 1);
    setCarousel({ ...carousel, slides: newSlides });
    setCurrentSlideIndex(index + 1);
    toast({ title: "Slide duplicado!" });
  };

  const moveSlide = (index: number, direction: number) => {
    if (!carousel) return;
    const newIndex = index + direction;
    if (newIndex < 0 || newIndex >= carousel.slides.length) return;

    const newSlides = [...carousel.slides];
    const [movedSlide] = newSlides.splice(index, 1);
    newSlides.splice(newIndex, 0, movedSlide);
    newSlides.forEach((s, i) => s.numero = i + 1);

    setCarousel({ ...carousel, slides: newSlides });
    setCurrentSlideIndex(newIndex);
  };

  const handleCloudSave = async () => {
    if (!carousel || !user) return;
    const result = await saveCarousel(carousel, user.id, brand);
    if (result && result.id) {
      setCarousel({ ...carousel, id: result.id });
    }
  };

  const scrollToDesign = () => {
    const designPanel = document.getElementById("design-settings-card");
    if (designPanel) {
      designPanel.scrollIntoView({ behavior: "smooth", block: "center" });
    }
  };


  // Load initial data from navigation state
  useEffect(() => {
    if (state?.preselectedFormat) {
      const validFormats = ['carousel', 'single_post', 'stories', 'reels_script'];
      if (validFormats.includes(state.preselectedFormat)) {
        setContentFormat(state.preselectedFormat as ContentFormat);
      }
    }
    if (state?.initialData && !carousel) {
      setCarousel(state.initialData);
      if (state.metadata?.topic) setTopic(state.metadata.topic);
      if (state.metadata?.theme) setTopic(state.metadata.theme);
      if (state.metadata?.postType) setPostType(state.metadata.postType);
      if (state.metadata?.contentPillar) setContentPillar(state.metadata.contentPillar);
      if (state.metadata?.offer) setCustomInstructions(`Oferta / CTA: ${state.metadata.offer}`);

      // Auto-generate designs if requested
      if (state.autoGenerateDesign) {
        toast({ title: "Iniciando geração visual...", description: "Aplicando sua identidade visual em todos os slides." });
        handleGenerateAllDesigns();
      }
    }
  }, [state, carousel, setCarousel, toast]);

  // Week content form
  const [weekTopics, setWeekTopics] = useState<{ topic: string; postType: PostType; contentPillar: string }[]>([
    { topic: "", postType: "STORYTELLING_RESULTADO", contentPillar: "Autoridade" },
    { topic: "", postType: "CONTRA_INTUITIVO", contentPillar: "Educativo" },
    { topic: "", postType: "QUEBRA_OBJECAO", contentPillar: "Conexão/Bastidores" },
    { topic: "", postType: "LISTA_AUTORIDADE", contentPillar: "Autoridade" },
    { topic: "", postType: "CTA_DIRETO", contentPillar: "Conversão/Venda" },
  ]);

  const handleGenerate = async () => {
    if (!topic.trim()) {
      toast({ variant: "destructive", title: "Digite um tema" });
      return;
    }
    await generateCarousel(topic, postType, contentPillar, customInstructions, undefined, funnelStage, ctaStyle, narrativeElement, contentFormat);
  };

  const handleGenerateWeek = async () => {
    const validTopics = weekTopics.filter(t => t.topic.trim());
    if (validTopics.length === 0) {
      toast({ variant: "destructive", title: "Adicione pelo menos um tema" });
      return;
    }
    await generateWeekContent(validTopics);
  };

  const handleEditWeekItem = (item: WeekContent) => {
    setEditingWeekItem(item.id);
    selectWeekContentForEdit(item.id);
  };

  const handleBackToWeekList = () => {
    setEditingWeekItem(null);
    resetCarousel();
  };

  const handleGenerateDesign = async (index: number) => {
    await generateSlideDesign(index, designSettings.style, {
      primary: designSettings.primaryColor,
      secondary: designSettings.secondaryColor,
    }, designSettings.fontFamily, carousel?.slides[index]?.backgroundImageUrl);
  };

  const handleSelectPhoto = (index: number) => {
    setPhotoTargetIndex(index);
    setShowPhotoDialog(true);
  };

  const onPhotoSelected = (url: string) => {
    if (photoTargetIndex !== null) {
      updateSlide(photoTargetIndex, { backgroundImageUrl: url });
      setPhotoTargetIndex(null);
    }
  };

  const handleGenerateAllDesigns = async () => {
    await generateAllSlideDesigns();
  };

  const updateWeekTopic = (index: number, updates: Partial<{ topic: string; postType: PostType; contentPillar: string }>) => {
    setWeekTopics(prev => prev.map((t, i) => i === index ? { ...t, ...updates } : t));
  };

  const addWeekTopic = () => {
    if (weekTopics.length < 7) {
      setWeekTopics(prev => [...prev, { topic: "", postType: "LISTA_AUTORIDADE", contentPillar: "Educativo" }]);
    }
  };

  const removeWeekTopic = (index: number) => {
    if (weekTopics.length > 1) {
      setWeekTopics(prev => prev.filter((_, i) => i !== index));
    }
  };

  const handleCopyLegenda = async () => {
    if (!carousel?.legenda) return;
    await navigator.clipboard.writeText(carousel.legenda);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
    toast({ title: "Legenda copiada!" });
  };

  const handleSave = async () => {
    if (!carousel) return;

    const result = await saveGeneration({
      tipo: "post",
      subtipo: "carrossel",
      specialist: "social_media_manager",
      titulo: carousel.titulo,
      output_content: JSON.stringify(carousel),
      input_data: { topic, postType, contentPillar },
      favorito: false,
      tags: [postType.toLowerCase(), contentPillar.toLowerCase()],
    });

    if (!result.error && result.data?.id) {
      setSavedGenerationId(result.data.id);
    }

    toast({ title: "Salvo com sucesso!" });
  };

  const handleSchedule = async (data: { date: string; tipo: string; titulo: string }) => {
    await addCalendarItem({
      data: data.date,
      tipo: data.tipo,
      titulo: data.titulo,
      generation_id: savedGenerationId || undefined,
    });
  };

  const handleDownloadZip = async () => {
    if (!carousel) return;

    const hasImages = carousel.slides.some(s => s.imageUrl);
    if (!hasImages) {
      toast({ variant: "destructive", title: "Gere os designs primeiro" });
      return;
    }

    setIsDownloading(true);
    try {
      await downloadCarouselAsZip(carousel.slides, carousel.titulo);
      toast({ title: "Download iniciado!" });
    } catch (error) {
      toast({
        variant: "destructive",
        title: "Erro no download",
        description: error instanceof Error ? error.message : "Tente novamente"
      });
    } finally {
      setIsDownloading(false);
    }
  };

  const currentSlide = carousel?.slides[currentSlideIndex];

  return (
    <div className="min-h-screen bg-gradient-to-br from-background via-background to-muted/20">
      {/* Header */}
      <header className="border-b bg-background/80 backdrop-blur-sm sticky top-0 z-50">
        <div className="container flex items-center justify-between h-14 px-4">
          <div className="flex items-center gap-3">
            {editingWeekItem ? (
              <Button variant="ghost" size="icon" onClick={handleBackToWeekList}>
                <ArrowLeft className="h-4 w-4" />
              </Button>
            ) : (
              <Button variant="ghost" size="icon" asChild>
                <Link to="/"><ArrowLeft className="h-4 w-4" /></Link>
              </Button>
            )}
            <div>
              <h1 className="font-semibold">
                {editingWeekItem ? "Editando Post" : `Gerador de ${CONTENT_FORMAT_LABELS[currentContentFormat] || 'Conteúdo'}`}
              </h1>
              <p className="text-xs text-muted-foreground">
                {editingWeekItem ? "Voltar para lista da semana" : "Crie conteúdo que converte"}
              </p>
            </div>
          </div>
          {carousel && (
            <div className="flex gap-2">
              {editingWeekItem && (
                <Button variant="outline" size="sm" onClick={handleBackToWeekList}>
                  <Check className="h-4 w-4 mr-2" /> Concluir Edição
                </Button>
              )}
              {!editingWeekItem && (
                <Button variant="outline" size="sm" onClick={resetCarousel}>
                  <RefreshCw className="h-4 w-4 mr-2" /> Novo
                </Button>
              )}
              <Button
                variant="outline"
                size="sm"
                onClick={handleDownloadZip}
                disabled={isDownloading || !carousel.slides.some(s => s.imageUrl)}
              >
                {isDownloading ? (
                  <Loader2 className="h-4 w-4 animate-spin" />
                ) : (
                  <><Download className="h-4 w-4 mr-2" /> ZIP</>
                )}
              </Button>
              <Button variant="outline" size="sm" onClick={() => setShowScheduleDialog(true)}>
                <CalendarPlus className="h-4 w-4 mr-2" /> Agendar
              </Button>
              <Button size="sm" onClick={handleSave}>
                <Save className="h-4 w-4 mr-2" /> Salvar
              </Button>
            </div>
          )}
        </div>
      </header>

      <main className="container px-4 py-6">
        {/* Week content list view */}
        {weekContent.length > 0 && !carousel && !editingWeekItem ? (
          <div className="max-w-4xl mx-auto space-y-6">
            <div className="flex items-center justify-between">
              <div>
                <h2 className="text-xl font-bold">Semana Gerada</h2>
                <p className="text-sm text-muted-foreground">Clique em um post para editar</p>
              </div>
              <Button variant="outline" onClick={resetWeekContent}>
                <RefreshCw className="h-4 w-4 mr-2" /> Nova Semana
              </Button>
            </div>

            <div className="grid gap-4">
              {weekContent.map((item, index) => (
                <Card
                  key={item.id}
                  className="cursor-pointer hover:border-primary transition-colors"
                  onClick={() => handleEditWeekItem(item)}
                >
                  <CardContent className="p-4">
                    <div className="flex items-center justify-between">
                      <div className="flex items-center gap-3">
                        <div className="w-10 h-10 rounded-lg bg-primary/10 flex items-center justify-center">
                          <span className="font-semibold text-primary">{index + 1}</span>
                        </div>
                        <div>
                          <p className="font-medium line-clamp-1">{item.carousel?.titulo || item.topic}</p>
                          <div className="flex gap-2 mt-1">
                            <Badge variant="outline" className="text-xs">{POST_TYPE_LABELS[item.postType]}</Badge>
                            <Badge variant="secondary" className="text-xs">{item.contentPillar}</Badge>
                          </div>
                        </div>
                      </div>
                      <div className="flex items-center gap-2">
                        <Badge variant={item.status === "edited" ? "default" : "secondary"}>
                          {item.status === "edited" ? "Editado" : "Gerado"}
                        </Badge>
                        <Edit3 className="h-4 w-4 text-muted-foreground" />
                      </div>
                    </div>
                  </CardContent>
                </Card>
              ))}
            </div>
          </div>
        ) : !carousel ? (
          <div className="max-w-4xl mx-auto pt-6 space-y-6 animate-in fade-in slide-in-from-bottom-4 duration-500">
            {/* Header */}
            <div className="text-center space-y-3">
              <div className="inline-flex items-center justify-center p-3 bg-primary/10 rounded-full mb-2">
                <Sparkles className="w-8 h-8 text-primary" />
              </div>
              <h1 className="text-3xl md:text-4xl font-bold tracking-tight text-foreground">
                Crie seu Conteúdo Estratégico
              </h1>
              <p className="text-base text-muted-foreground max-w-2xl mx-auto">
                Escolha o formato, preencha os campos e a IA criará conteúdo de alta conversão com design profissional.
              </p>
            </div>

            {/* STEP 1: Formato */}
            <Card className="border-2 shadow-lg">
              <CardHeader className="pb-3">
                <CardTitle className="text-base flex items-center gap-2">
                  <span className="flex items-center justify-center w-7 h-7 rounded-full bg-primary text-primary-foreground text-xs font-bold">1</span>
                  Qual formato de conteúdo?
                </CardTitle>
                <CardDescription>Cada formato gera conteúdo e design otimizado para sua finalidade.</CardDescription>
              </CardHeader>
              <CardContent className="pt-0">
                <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
                  {(Object.keys(CONTENT_FORMAT_LABELS) as ContentFormat[]).map((fmt) => (
                    <button
                      key={fmt}
                      onClick={() => setContentFormat(fmt)}
                      className={cn(
                        "flex flex-col items-center gap-2 p-4 rounded-xl border-2 text-center transition-all hover:shadow-md",
                        contentFormat === fmt
                          ? "border-primary bg-primary/5 shadow-sm"
                          : "border-muted hover:border-primary/30"
                      )}
                    >
                      <span className="text-3xl">{CONTENT_FORMAT_ICONS[fmt]}</span>
                      <p className="font-semibold text-sm">{CONTENT_FORMAT_LABELS[fmt]}</p>
                      <p className="text-[10px] text-muted-foreground leading-tight">{CONTENT_FORMAT_DESCRIPTIONS[fmt]}</p>
                    </button>
                  ))}
                </div>
              </CardContent>
            </Card>

            {/* Templates Prontos (atalhos) */}
            <Card className="border border-dashed border-primary/30 bg-primary/[0.02]">
              <CardHeader className="pb-2">
                <CardTitle className="text-sm flex items-center gap-2 text-primary/80">
                  <Lightbulb className="h-4 w-4" />
                  Templates Prontos — clique para preencher automaticamente
                </CardTitle>
              </CardHeader>
              <CardContent className="pt-0">
                <div className="flex flex-wrap gap-2">
                  {[
                    { label: "Levantada de Mão", emoji: "🖐️", format: "stories" as ContentFormat, funnel: "EVENTOS_DOR" as FunnelStage, type: "CTA_DIRETO" as PostType, cta: "PALAVRA_CHAVE" as CtaStyle, topic: "Resultado real de paciente + 3 pilares do método + CTA para comentar palavra-chave. Objetivo: gerar leads quentes nos stories." },
                    { label: "Mito vs Verdade", emoji: "🧠", format: "carousel" as ContentFormat, funnel: "ALCANCE" as FunnelStage, type: "MITO_VS_VERDADE" as PostType, cta: "SALVAR_COMPARTILHAR" as CtaStyle, topic: "Desmistificar uma crença popular sobre alimentação/nutrição que prejudica o resultado das pacientes." },
                    { label: "Storytelling Resultado", emoji: "✨", format: "carousel" as ContentFormat, funnel: "EVENTOS_DOR" as FunnelStage, type: "STORYTELLING_RESULTADO" as PostType, cta: "PALAVRA_CHAVE" as CtaStyle, topic: "Contar a história de transformação de uma paciente — da dor inicial ao resultado alcançado com o acompanhamento nutricional." },
                    { label: "Reels: 3 Erros", emoji: "🎬", format: "reels_script" as ContentFormat, funnel: "ALCANCE" as FunnelStage, type: "LISTA_AUTORIDADE" as PostType, cta: "SALVAR_COMPARTILHAR" as CtaStyle, topic: "3 erros que sabotam o emagrecimento e que a maioria das pessoas comete sem perceber. Tom conversacional, como amiga." },
                    { label: "Post de Oferta", emoji: "🎯", format: "single_post" as ContentFormat, funnel: "VENDA_DIRETA" as FunnelStage, type: "CTA_DIRETO" as PostType, cta: "LINK_BIO" as CtaStyle, topic: "Post direto de venda do plano de acompanhamento nutricional — mostrar o que inclui, para quem é, e por que agora é o momento." },
                    { label: "Quebra de Objeção", emoji: "🛡️", format: "carousel" as ContentFormat, funnel: "EVENTOS_DOR" as FunnelStage, type: "QUEBRA_OBJECAO" as PostType, cta: "DM" as CtaStyle, topic: "Destruir a objeção 'não tenho tempo para cuidar da alimentação' mostrando que o acompanhamento se adapta à rotina." },
                    { label: "Stories: Rotina", emoji: "📱", format: "stories" as ContentFormat, funnel: "PRINCIPIOS_VALORES" as FunnelStage, type: "ROTINA_PRATICA" as PostType, cta: "LEVANTADA_MAO" as CtaStyle, topic: "Mostrar bastidores da rotina profissional — consulta, estudo de caso, preparo de plano alimentar. Humanizar e gerar conexão." },
                    { label: "Antes e Depois", emoji: "🔄", format: "carousel" as ContentFormat, funnel: "EVENTOS_DOR" as FunnelStage, type: "ANTES_DEPOIS_CONCEITUAL" as PostType, cta: "PALAVRA_CHAVE" as CtaStyle, topic: "Mostrar a transformação de mindset e hábitos de uma paciente (sem fotos de corpo) — do caos alimentar para a organização e equilíbrio." },
                  ].map((tpl) => (
                    <button
                      key={tpl.label}
                      onClick={() => {
                        setContentFormat(tpl.format);
                        setFunnelStage(tpl.funnel);
                        setPostType(tpl.type);
                        setCtaStyle(tpl.cta);
                        setTopic(tpl.topic);
                      }}
                      className="inline-flex items-center gap-1.5 px-3 py-2 rounded-lg border border-primary/20 bg-white hover:bg-primary/5 hover:border-primary/40 transition-all text-xs font-medium text-foreground"
                    >
                      <span>{tpl.emoji}</span> {tpl.label}
                    </button>
                  ))}
                </div>
              </CardContent>
            </Card>

            {/* STEP 2: Tema */}
            <Card className="border-2 shadow-lg">
              <CardHeader className="pb-3">
                <CardTitle className="text-base flex items-center gap-2">
                  <span className="flex items-center justify-center w-7 h-7 rounded-full bg-primary text-primary-foreground text-xs font-bold">2</span>
                  Qual é o tema {contentFormat === 'reels_script' ? 'do vídeo' : contentFormat === 'stories' ? 'da sequência' : contentFormat === 'single_post' ? 'do post' : 'do carrossel'}?
                </CardTitle>
                <CardDescription>Seja específica: inclua o assunto, a dor ou o resultado que quer abordar.</CardDescription>
              </CardHeader>
              <CardContent className="pt-0 space-y-3">
                <Textarea
                  value={topic}
                  onChange={(e) => setTopic(e.target.value)}
                  placeholder={
                    contentFormat === 'reels_script'
                      ? "Ex: Falar sobre os 3 erros que fazem a dieta falhar — tom conversacional, como se estivesse falando com uma amiga..."
                      : contentFormat === 'stories'
                      ? "Ex: Sequência sobre como o estresse engorda — usando enquete no 1º story e CTA no final para DM..."
                      : contentFormat === 'single_post'
                      ? "Ex: Frase de impacto sobre por que contar caloria não funciona para regulação hormonal..."
                      : "Ex: Por que cortar carboidrato não emagrece — e o que fazer no lugar para mulheres com resistência insulínica..."
                  }
                  className="min-h-[100px] text-base p-4 resize-none border-muted focus-visible:ring-primary/20 bg-muted/5 rounded-xl"
                />
                <div className="flex items-center justify-between">
                  <span className="text-xs text-muted-foreground flex items-center gap-1">
                    <Lightbulb className="w-3 h-3" /> Quanto mais específico, melhor o resultado
                  </span>
                  <span className="text-xs text-muted-foreground">{topic.length} caracteres</span>
                </div>
              </CardContent>
            </Card>

            {/* STEP 2: Funil */}
            <Card className="border-2 shadow-lg">
              <CardHeader className="pb-3">
                <CardTitle className="text-base flex items-center gap-2">
                  <span className="flex items-center justify-center w-7 h-7 rounded-full bg-primary text-primary-foreground text-xs font-bold">3</span>
                  Objetivo no funil?
                </CardTitle>
                <CardDescription>Escolha onde esse post se encaixa na sua estratégia de captação e conversão.</CardDescription>
              </CardHeader>
              <CardContent className="pt-0">
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                  {(Object.keys(FUNNEL_STAGE_LABELS) as FunnelStage[]).map((stage) => (
                    <button
                      key={stage}
                      onClick={() => setFunnelStage(stage)}
                      className={cn(
                        "flex items-start gap-3 p-4 rounded-xl border-2 text-left transition-all hover:shadow-md",
                        funnelStage === stage
                          ? "border-primary bg-primary/5 shadow-sm"
                          : "border-muted hover:border-primary/30"
                      )}
                    >
                      <span className="text-2xl mt-0.5">{FUNNEL_STAGE_ICONS[stage]}</span>
                      <div>
                        <p className="font-semibold text-sm">{FUNNEL_STAGE_LABELS[stage]}</p>
                        <p className="text-xs text-muted-foreground mt-0.5">{FUNNEL_STAGE_DESCRIPTIONS[stage]}</p>
                      </div>
                    </button>
                  ))}
                </div>
              </CardContent>
            </Card>

            {/* STEP 3: Tipo de Post */}
            <Card className="border-2 shadow-lg">
              <CardHeader className="pb-3">
                <CardTitle className="text-base flex items-center gap-2">
                  <span className="flex items-center justify-center w-7 h-7 rounded-full bg-primary text-primary-foreground text-xs font-bold">4</span>
                  Tipo de post
                </CardTitle>
                <CardDescription>Cada tipo usa uma estrutura narrativa diferente para máximo impacto.</CardDescription>
              </CardHeader>
              <CardContent className="pt-0">
                <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-2">
                  {(Object.keys(POST_TYPE_LABELS) as PostType[]).map((type) => (
                    <button
                      key={type}
                      onClick={() => setPostType(type)}
                      className={cn(
                        "p-3 rounded-xl border-2 text-left transition-all hover:shadow-sm",
                        postType === type
                          ? "border-primary bg-primary/5"
                          : "border-muted hover:border-primary/30"
                      )}
                    >
                      <p className="font-semibold text-sm">{POST_TYPE_LABELS[type]}</p>
                      <p className="text-[11px] text-muted-foreground mt-0.5 line-clamp-2">{POST_TYPE_DESCRIPTIONS[type]}</p>
                    </button>
                  ))}
                </div>
              </CardContent>
            </Card>

            {/* STEP 4: CTA e Narrativa (colapsável) */}
            <Card className="border-2 shadow-lg">
              <CardHeader className="pb-3 cursor-pointer" onClick={() => setShowAdvanced(!showAdvanced)}>
                <CardTitle className="text-base flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <span className="flex items-center justify-center w-7 h-7 rounded-full bg-primary text-primary-foreground text-xs font-bold">5</span>
                    Ajustes avançados
                  </div>
                  <ChevronRight className={cn("h-5 w-5 text-muted-foreground transition-transform", showAdvanced && "rotate-90")} />
                </CardTitle>
                <CardDescription>CTA, elemento narrativo e instruções extras (opcional).</CardDescription>
              </CardHeader>

              {showAdvanced && (
                <CardContent className="pt-0 space-y-5">
                  {/* CTA Style */}
                  <div className="space-y-2">
                    <Label className="text-sm font-semibold">Estilo de CTA</Label>
                    <div className="grid grid-cols-2 sm:grid-cols-3 gap-2">
                      {(Object.keys(CTA_STYLE_LABELS) as CtaStyle[]).map((style) => (
                        <button
                          key={style}
                          onClick={() => setCtaStyle(style)}
                          className={cn(
                            "p-2.5 rounded-lg border-2 text-xs font-medium transition-all",
                            ctaStyle === style
                              ? "border-primary bg-primary/5 text-primary"
                              : "border-muted hover:border-primary/30"
                          )}
                        >
                          {CTA_STYLE_LABELS[style]}
                        </button>
                      ))}
                    </div>
                  </div>

                  {/* Narrative Element */}
                  <div className="space-y-2">
                    <Label className="text-sm font-semibold">Elemento Narrativo</Label>
                    <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 gap-2">
                      {(Object.keys(NARRATIVE_ELEMENT_LABELS) as NarrativeElement[]).map((el) => (
                        <button
                          key={el}
                          onClick={() => setNarrativeElement(el)}
                          className={cn(
                            "p-2.5 rounded-lg border-2 text-xs font-medium transition-all",
                            narrativeElement === el
                              ? "border-primary bg-primary/5 text-primary"
                              : "border-muted hover:border-primary/30"
                          )}
                        >
                          {NARRATIVE_ELEMENT_LABELS[el]}
                        </button>
                      ))}
                    </div>
                  </div>

                  {/* Custom Instructions */}
                  <div className="space-y-2">
                    <Label className="text-sm font-semibold">Instruções extras (opcional)</Label>
                    <Textarea
                      value={customInstructions}
                      onChange={(e) => setCustomInstructions(e.target.value)}
                      placeholder="Ex: Mencionar a consulta de R$297 como CTA. Usar tom mais científico. Focar em saúde intestinal..."
                      className="min-h-[80px] text-sm resize-none"
                    />
                  </div>
                </CardContent>
              )}
            </Card>

            {/* Generate Button */}
            <div className="flex justify-center pt-2 pb-8">
              <Button
                onClick={handleGenerate}
                disabled={isGenerating || !topic.trim()}
                size="lg"
                className="rounded-full px-10 py-6 text-base font-bold shadow-xl hover:shadow-2xl transition-all hover:scale-[1.02] bg-gradient-to-r from-primary to-primary/80"
              >
                {isGenerating ? (
                  <><Loader2 className="mr-2 h-5 w-5 animate-spin" /> Gerando {CONTENT_FORMAT_LABELS[contentFormat]}...</>
                ) : (
                  <>
                    <Wand2 className="mr-2 h-5 w-5" /> Gerar {CONTENT_FORMAT_LABELS[contentFormat]} Estratégico <ArrowRight className="ml-2 w-5 h-5" />
                  </>
                )}
              </Button>
            </div>
          </div>
        ) : (
          /* Carousel Editor */
          <div className="space-y-6">
            {carousel && (
              <div className="max-w-6xl mx-auto animate-in fade-in slide-in-from-bottom-4 duration-700">
                {/* Estratégia Ativa Indicator */}
                <div className="mb-8 flex flex-col md:flex-row items-center justify-between p-6 bg-white/40 backdrop-blur-md border border-primary/20 rounded-[32px] shadow-sm gap-4">
                  <div className="flex items-center gap-4">
                    <div className="p-3 bg-primary/10 rounded-2xl">
                      <Target className="h-6 w-6 text-primary" />
                    </div>
                    <div>
                      <p className="text-[10px] font-black uppercase tracking-[0.2em] text-primary/60">Estratégia Ativa</p>
                      <h2 className="font-extrabold text-xl tracking-tight">{carousel.titulo}</h2>
                    </div>
                  </div>
                  <div className="flex gap-2 flex-wrap">
                    <Badge variant="secondary" className="bg-primary/10 text-primary border-none px-4 py-1.5 rounded-xl font-bold">{CONTENT_FORMAT_LABELS[currentContentFormat]}</Badge>
                    <Badge variant="secondary" className="bg-primary/10 text-primary border-none px-4 py-1.5 rounded-xl font-bold">{POST_TYPE_LABELS[postType] || 'Estratégia'}</Badge>
                    <Badge variant="outline" className="border-primary/20 px-4 py-1.5 rounded-xl font-medium">{FUNNEL_STAGE_LABELS[funnelStage] || contentPillar}</Badge>
                    {ctaStyle !== 'auto' && <Badge variant="outline" className="border-emerald-200 text-emerald-700 px-4 py-1.5 rounded-xl font-medium">{CTA_STYLE_LABELS[ctaStyle]}</Badge>}
                  </div>
                </div>

                <div className="grid lg:grid-cols-[1fr_320px] gap-10 items-start">
                  {/* Column 1: Canva-style Editor */}
                  <div className="space-y-8">
                    <div className="flex flex-col w-full">
                      <div className="mb-4">
                        <SlideToolbar
                          onEditContent={() => { }} // Direct editing is now always on
                          onEditStyle={scrollToDesign}
                          onDelete={() => removeSlide(currentSlideIndex)}
                          onDuplicate={() => duplicateSlide(currentSlideIndex)}
                          onMoveLeft={() => moveSlide(currentSlideIndex, -1)}
                          onMoveRight={() => moveSlide(currentSlideIndex, 1)}
                          canMoveLeft={currentSlideIndex > 0}
                          canMoveRight={currentSlideIndex < (carousel?.slides?.length || 0) - 1}
                          currentSlideText={carousel?.slides[currentSlideIndex]?.headline || ""}
                          onUpdateText={(newText) => updateSlide(currentSlideIndex, { headline: newText })}
                        />
                      </div>

                      {/* Direct Editor Stage */}
                      {currentContentFormat === 'reels_script' ? (
                        /* Reels Script View */
                        <div className="bg-slate-50/50 dark:bg-slate-900/10 p-6 md:p-10 rounded-[32px] border border-slate-200/40 shadow-[inset_0_2px_10px_rgba(0,0,0,0.02)] min-h-[400px]">
                          <div className="max-w-lg mx-auto space-y-4">
                            <div className="flex items-center gap-3 mb-6">
                              <div className="w-10 h-10 rounded-full bg-red-500/10 flex items-center justify-center">
                                <span className="text-lg">🎬</span>
                              </div>
                              <div>
                                <p className="text-xs font-bold uppercase tracking-wider text-red-500/70">Seção {currentSlideIndex + 1} / {carousel.slides.length}</p>
                                <p className="text-sm font-semibold text-muted-foreground">
                                  {currentSlideIndex === 0 ? 'Gancho (0-3s)' : currentSlideIndex === carousel.slides.length - 1 ? 'Fechamento + CTA' : `Desenvolvimento (${currentSlideIndex * 8}-${(currentSlideIndex + 1) * 8}s)`}
                                </p>
                              </div>
                            </div>

                            <div className="space-y-4">
                              <div className="bg-white rounded-2xl p-5 border border-slate-200 shadow-sm space-y-2">
                                <p className="text-[10px] font-bold uppercase tracking-widest text-primary/60">Texto na Tela</p>
                                <div className="text-xl font-bold text-foreground">{carousel.slides[currentSlideIndex]?.headline || '—'}</div>
                              </div>

                              <div className="bg-white rounded-2xl p-5 border border-slate-200 shadow-sm space-y-2">
                                <p className="text-[10px] font-bold uppercase tracking-widest text-blue-500/60">Script Falado</p>
                                <div className="text-base text-foreground leading-relaxed whitespace-pre-line">{carousel.slides[currentSlideIndex]?.subtexto || '—'}</div>
                              </div>

                              {carousel.slides[currentSlideIndex]?.destaque && (
                                <div className="bg-amber-50 rounded-2xl p-4 border border-amber-200 space-y-1">
                                  <p className="text-[10px] font-bold uppercase tracking-widest text-amber-600/60">Indicação Técnica</p>
                                  <div className="text-sm font-medium text-amber-800">{carousel.slides[currentSlideIndex]?.destaque}</div>
                                </div>
                              )}
                            </div>
                          </div>
                        </div>
                      ) : (
                        /* Visual Slide Editor (Carousel, Single Post, Stories) */
                        <div className="relative group transition-all duration-700 ease-in-out bg-slate-50/50 dark:bg-slate-900/10 p-4 md:p-16 rounded-[48px] border border-slate-200/40 flex justify-center shadow-[inset_0_2px_10px_rgba(0,0,0,0.02)] min-h-[500px]">
                          <div className="relative">
                            {/* Realistic Sombra */}
                            <div className="absolute -inset-4 bg-gradient-to-tr from-primary/10 via-transparent to-primary/5 blur-3xl opacity-50" />

                            <div
                              id="active-slide-container"
                              className={cn(
                                "relative bg-white rounded-xl shadow-[0_30px_60px_-15px_rgba(0,0,0,0.2)] overflow-hidden ring-1 ring-black/5 transform hover:scale-[1.01] transition-all duration-500",
                                currentContentFormat === 'stories'
                                  ? "w-[270px] aspect-[9/16]"
                                  : "w-[340px] aspect-[4/5]"
                              )}
                            >
                            <CarouselSlideEditor
                              slide={carousel.slides[currentSlideIndex]}
                              index={currentSlideIndex}
                              onUpdate={updateSlide}
                              onSelectBackground={() => handleSelectPhoto(currentSlideIndex)}
                              onRefine={refineText}
                            />

                            {/* Carousel Indicator Bolinhas */}
                            <div className="absolute bottom-4 left-0 right-0 flex justify-center gap-1.5 z-20 pointer-events-none">
                              {carousel.slides.map((_, i) => (
                                <div
                                  key={i}
                                  className={cn(
                                    "w-1.5 h-1.5 rounded-full transition-all duration-300",
                                    i === currentSlideIndex ? "bg-primary w-4 scale-110" : "bg-slate-200"
                                  )}
                                />
                              ))}
                            </div>
                          </div>
                        </div>
                      </div>
                      )}

                      <div className="mt-8 flex flex-wrap justify-center gap-4">
                        {currentContentFormat !== 'reels_script' && (
                        <Button
                          onClick={() => exportSlideAsImage('active-slide-container', `slide-${currentSlideIndex + 1}`)}
                          className="h-14 px-8 gap-3 rounded-[20px] shadow-lg hover:shadow-xl transition-all border-slate-200 bg-white"
                          variant="outline"
                        >
                          <Download className="h-5 w-5 text-primary" /> Exportar {currentContentFormat === 'stories' ? 'Story' : 'Slide'} HD
                        </Button>
                        )}

                        <Button
                          onClick={handleCloudSave}
                          disabled={isSavingCloud}
                          className="h-14 px-8 gap-3 rounded-[20px] shadow-xl hover:shadow-2xl transition-all bg-gradient-to-r from-primary to-primary/80 border-none"
                        >
                          {isSavingCloud ? <Loader2 className="h-5 w-5 animate-spin" /> : <Save className="h-5 w-5" />}
                          {isSavingCloud ? "Salvando..." : "Salvar na Estratégia"}
                        </Button>
                      </div>
                    </div>

                    {/* Slide Selector Strip */}
                    <div className="flex items-center justify-between gap-4 p-5 bg-white/90 backdrop-blur-xl rounded-[32px] border border-slate-200/50 shadow-xl overflow-hidden animate-in slide-in-from-bottom-8 duration-1000">
                      <Button
                        variant="ghost"
                        size="icon"
                        className="rounded-full h-12 w-12 hover:bg-primary/5 transition-colors"
                        onClick={() => setCurrentSlideIndex(Math.max(0, currentSlideIndex - 1))}
                        disabled={currentSlideIndex === 0}
                      >
                        <ChevronLeft className="h-8 w-8 text-slate-400" />
                      </Button>

                      <ScrollArea className="flex-1 w-full max-w-lg">
                        <div className="flex gap-4 justify-center py-2 px-6">
                          {carousel.slides.map((slide, i) => (
                            <button
                              key={i}
                              onClick={() => setCurrentSlideIndex(i)}
                              className={cn(
                                "min-w-[64px] h-20 rounded-2xl text-xs font-black transition-all border-4 relative overflow-hidden group/btn",
                                i === currentSlideIndex
                                  ? "border-primary bg-primary text-primary-foreground scale-110 shadow-xl"
                                  : "bg-white border-slate-50 text-slate-400 hover:border-slate-100 hover:text-slate-600"
                              )}
                            >
                              {i + 1}
                              {slide.imageUrl && (
                                <div className="absolute top-1 right-1">
                                  <div className="w-2 h-2 bg-green-500 rounded-full shadow-[0_0_8px_rgba(34,197,94,0.6)]" />
                                </div>
                              )}
                              <div className="absolute inset-0 bg-primary/5 opacity-0 group-hover/btn:opacity-100 transition-opacity" />
                            </button>
                          ))}
                          <Button
                            variant="ghost"
                            onClick={() => addSlide(carousel.slides.length - 1)}
                            className="min-w-[64px] h-20 rounded-2xl border-4 border-dashed border-slate-100 text-slate-300 hover:text-primary hover:border-primary/30 transition-all p-0 bg-slate-50/50"
                          >
                            <Plus className="h-8 w-8" />
                          </Button>
                        </div>
                      </ScrollArea>

                      <Button
                        variant="ghost"
                        size="icon"
                        className="rounded-full h-12 w-12 hover:bg-primary/5 transition-colors"
                        onClick={() => setCurrentSlideIndex(Math.min(carousel.slides.length - 1, currentSlideIndex + 1))}
                        disabled={currentSlideIndex === carousel.slides.length - 1}
                      >
                        <ChevronRight className="h-8 w-8 text-slate-400" />
                      </Button>
                    </div>
                  </div>

                  {/* Column 2: Brand & Copy */}
                  <div className="space-y-8 animate-in slide-in-from-right-8 duration-700">
                    <Card className="border-none shadow-2xl bg-white/95 backdrop-blur-xl overflow-hidden rounded-[32px] border border-white/20">
                      <CardHeader className="bg-primary/5 pb-4 border-b border-primary/10">
                        <CardTitle className="text-sm font-black flex items-center gap-2 uppercase tracking-widest text-primary/80">
                          <Palette className="h-4 w-4" /> Kit de Marca
                        </CardTitle>
                      </CardHeader>
                      <CardContent className="p-8 space-y-8">
                        <div className="space-y-4">
                          <Label className="text-[10px] font-black uppercase tracking-[0.2em] opacity-40">Tipografia</Label>
                          <div className="p-4 bg-slate-50/50 border border-slate-100 rounded-2xl flex items-center justify-between group cursor-default">
                            <span className="font-extrabold tracking-tight text-slate-800">{brand.fontHeading}</span>
                            <Badge variant="secondary" className="bg-primary/10 text-primary border-none text-[9px] font-black uppercase">Ativo</Badge>
                          </div>
                        </div>

                        <div className="space-y-4">
                          <Label className="text-[10px] font-black uppercase tracking-[0.2em] opacity-40">Paleta Cromática</Label>
                          <div className="grid grid-cols-2 gap-4">
                            <div className="p-5 bg-white border border-slate-100 rounded-[24px] space-y-3 shadow-sm hover:shadow-md transition-shadow">
                              <div className="h-14 rounded-2xl shadow-inner relative group" style={{ backgroundColor: brand.primary }}>
                                <div className="absolute inset-0 bg-white/10 opacity-0 group-hover:opacity-100 transition-opacity rounded-2xl" />
                              </div>
                              <span className="text-[10px] font-black font-mono text-center block opacity-40 group-hover:opacity-100 transition-opacity">{brand.primary}</span>
                            </div>
                            <div className="p-5 bg-white border border-slate-100 rounded-[24px] space-y-3 shadow-sm hover:shadow-md transition-shadow">
                              <div className="h-14 rounded-2xl shadow-inner relative group" style={{ backgroundColor: brand.secondary }}>
                                <div className="absolute inset-0 bg-white/10 opacity-0 group-hover:opacity-100 transition-opacity rounded-2xl" />
                              </div>
                              <span className="text-[10px] font-black font-mono text-center block opacity-40 group-hover:opacity-100 transition-opacity">{brand.secondary}</span>
                            </div>
                          </div>
                        </div>

                        <Button
                          variant="outline"
                          className="w-full h-14 rounded-2xl font-bold gap-4 border-slate-200 hover:bg-primary hover:text-white hover:border-primary transition-all shadow-sm group"
                          onClick={() => handleSelectPhoto(currentSlideIndex)}
                        >
                          <Images className="h-5 w-5 text-primary group-hover:text-white transition-colors" /> Personalizar Fundo
                        </Button>
                      </CardContent>
                    </Card>

                    <Card className="border-none shadow-2xl bg-white/95 backdrop-blur-xl rounded-[32px] overflow-hidden border border-white/20">
                      <CardHeader className="pb-4 border-b bg-primary/5 border-primary/10">
                        <CardTitle className="text-sm font-black flex items-center gap-2 uppercase tracking-widest text-primary/80">
                          <Edit3 className="h-4 w-4" /> Copy de Elite
                        </CardTitle>
                      </CardHeader>
                      <CardContent className="p-8 space-y-6">
                        <div className="bg-slate-50/80 rounded-3xl p-6 border border-slate-100 shadow-inner">
                          <Textarea
                            value={carousel.legenda}
                            onChange={(e) => updateLegenda(e.target.value)}
                            className="min-h-[300px] text-sm leading-relaxed border-none bg-transparent resize-none p-0 focus-visible:ring-0 scrollbar-hide"
                            placeholder="Editando a copy persuasiva..."
                          />
                        </div>
                        <Button
                          variant="default"
                          className="w-full h-14 rounded-2xl font-black gap-4 shadow-xl shadow-primary/20 hover:scale-[1.02] transition-transform"
                          onClick={handleCopyLegenda}
                        >
                          <Copy className="h-5 w-5" /> Copiar Legenda
                        </Button>
                      </CardContent>
                    </Card>
                  </div>
                </div>
              </div>
            )}
          </div>
        )}
      </main>

      {/* Schedule Dialog */}
      <ScheduleDialog
        open={showScheduleDialog}
        onOpenChange={setShowScheduleDialog}
        onSchedule={handleSchedule}
        defaultTitle={carousel?.titulo || topic}
        defaultTipo="carrossel"
      />

      <PhotoSelectionDialog
        open={showPhotoDialog}
        onOpenChange={setShowPhotoDialog}
        onSelect={onPhotoSelected}
        selectedUrl={carousel?.slides[currentSlideIndex]?.backgroundImageUrl}
      />
    </div>
  );
}
