// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/get-profile.ts
import { createClient } from "npm:@supabase/supabase-js@^2.90.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_profile_default = defineTool({
  name: "get_profile",
  title: "Get profile & brand",
  description: "Return the signed-in nutritionist's profile: niche, persona, tone of voice, brand colors and fonts.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser(ctx).from("profiles").select("*").eq("user_id", ctx.getUserId()).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? {}, null, 2) }],
      structuredContent: { profile: data }
    };
  }
});

// src/lib/mcp/tools/list-products.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.90.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_products_default = defineTool2({
  name: "list_products",
  title: "List products",
  description: "List the signed-in user's products / offers (name, price, client type, product type, active flag).",
  inputSchema: {
    only_active: z.boolean().optional().describe("If true, return only products marked as active.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ only_active }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let q = supabaseForUser2(ctx).from("products").select("id, nome, descricao, ticket, tipo_cliente, tipo_produto, ativo, ordem").eq("user_id", ctx.getUserId()).order("ordem", { ascending: true });
    if (only_active) q = q.eq("ativo", true);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { products: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-content.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.90.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_content_default = defineTool3({
  name: "list_content",
  title: "List generated content",
  description: "List the user's AI-generated content pieces (posts, carousels, strategies) from the library. Filter by type or favorites.",
  inputSchema: {
    tipo: z2.string().optional().describe("Optional content type filter, e.g. 'post', 'carousel', 'strategy'."),
    only_favorites: z2.boolean().optional().describe("Return only favorited items."),
    limit: z2.number().int().min(1).max(100).optional().describe("Max results (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ tipo, only_favorites, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let q = supabaseForUser3(ctx).from("generations").select("id, tipo, subtipo, specialist, titulo, tags, favorito, output_content, created_at").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit ?? 20);
    if (tipo) q = q.eq("tipo", tipo);
    if (only_favorites) q = q.eq("favorito", true);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { items: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-calendar.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.90.1";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^3.25.76";
function supabaseForUser4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_calendar_default = defineTool4({
  name: "list_calendar",
  title: "List calendar items",
  description: "List scheduled content in the user's content planner within an optional date range (ISO YYYY-MM-DD).",
  inputSchema: {
    from: z3.string().optional().describe("Start date (YYYY-MM-DD), inclusive."),
    to: z3.string().optional().describe("End date (YYYY-MM-DD), inclusive."),
    status: z3.string().optional().describe("Optional status filter (e.g. 'draft', 'scheduled').")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ from, to, status }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let q = supabaseForUser4(ctx).from("calendar_items").select("id, data, tipo, status, titulo, notas, generation_id, created_at").eq("user_id", ctx.getUserId()).order("data", { ascending: true });
    if (from) q = q.gte("data", from);
    if (to) q = q.lte("data", to);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { items: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "niumihdrjnfyymncpxqf";
var mcp_default = defineMcp({
  name: "nutrisales-os-mcp",
  title: "NutriSales OS",
  version: "0.1.0",
  instructions: "Read-only access to the signed-in nutritionist's NutriSales OS workspace: profile & brand, products/offers, generated content library, and content planner calendar. Use `get_profile` for niche/persona context, `list_products` for the offer ladder, `list_content` to search past AI generations, and `list_calendar` for scheduled posts.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_profile_default, list_products_default, list_content_default, list_calendar_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
